In [2]:
#importing essential librabries

# data gathering,cleaning and analysis libraries
import pandas as pd
import numpy as np
# for converting datatype to json for API
import json

`Column` | Description
:-|:-
`match_id` |	Unique identifier for each match, used to link with match details.
`inning`|	Indicates the innings (1 or 2) in the match.
`batting_team`|Name of the team batting in the given inning.
`bowling_team`|	Name of the team bowling in the given inning.
`over`|	The over number in the current inning (e.g., 1, 2, ..., 20).
`ball`|	The ball number within the over (1 to 6).
`batter`|	Name of the player currently batting.
`bowler`	|Name of the player currently bowling.
`non_striker`|	Name of the non-striker at the other end of the pitch.
`batsman_runs`|	Number of runs scored```` by the batsman on the current delivery (can include 0 for dot balls or 4/6 for boundaries).
`extra_runs`	|Number of extra runs (such as no-balls, wides) on this delivery.
`total_runs`	|Total runs scored on this ball (sum of batsman runs and extra runs).
`extras_type`	|Type of extra run, if applicable (e.g., wide, no-ball, bye, legbye).
`is_wicket`	|Indicates if the delivery resulted in a wicket (1 for wicket, 0 for no wicket).
`player_dismissed`|	Name of the player dismissed on the ball (if applicable, otherwise null).
`dismissal_kind`	|Type of dismissal (e.g., bowled, caught, run out, LBW).
`fielder`	|Name of the fielder involved in the dismissal (for dismissals like catch, run out, etc.; null for dismissals not involving a fielder).

In [4]:
# Gathering IPL data from 2008-2024
ipl1=pd.read_csv(r"D:\IPL-Project--master\PROJECT_FOLDER\datasets\mod_deliveries.csv")
ipl1.sample(5)

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
184238,1216513,1,Punjab Kings,Chennai Super Kings,16,1,N Pooran,DJ Bravo,KL Rahul,2,0,2,NaN,0,NaN,NaN,NaN
166942,1175365,1,Kolkata Knight Riders,Delhi Capitals,1,5,NS Naik,S Lamichhane,CA Lynn,0,0,0,NaN,0,NaN,NaN,NaN
77486,598002,2,Chennai Super Kings,Mumbai Indians,2,5,MEK Hussey,MG Johnson,SK Raina,0,0,0,NaN,0,NaN,NaN,NaN
192880,1237177,2,Delhi Capitals,Mumbai Indians,19,5,K Rabada,KA Pollard,AR Patel,1,0,1,NaN,0,NaN,NaN,NaN
37602,419149,1,Delhi Capitals,Punjab Kings,7,6,KD Karthik,PP Chawla,DL Vettori,0,0,0,NaN,0,NaN,NaN,NaN

`Column`	|Description
:-|:-
`id`	|Unique identifier for each match, similar to match_id in the ball-by-ball dataset, useful for linking datasets.
`season`|	Year in which the IPL season took place.
`city`	|City where the match was played.
`date`	|Date of the match.
`match_type`|	Type of match (could indicate regular season, playoff, or final).
`player_of_match`|	Name of the player awarded "Player of the Match."
`venue`|	Stadium where the match was played.
`team1`	|Name of the first team (order doesn’t imply batting or bowling first).
`team2`	|Name of the second team.
`toss_winner`|	Team that won the toss.
`toss_decision`|	Decision taken by the toss-winning team (bat or field).
`winner`|Name of the team that won the match.
`result`|	Outcome type of the match (e.g., normal, tie, no result).
`result_margin`|	Margin by which the team won (e.g., runs or wickets).
`target_runs`	|Target runs set for the chasing team (null if not applicable).
`target_overs`	|Target overs if the match is shortened (e.g., in rain-affected matches; null if not applicable).
`super_over`	|Indicates if the match had a super over (1 for yes, 0 for no).
`method`	|Method used to determine the result in rain-affected games (e.g., Duckworth-Lewis-Stern, or null if not applicable).
`umpire1`	|Name of the first on-field umpire.
`umpire2`	|Name of the second on-field umpire.

In [6]:
ipl2=pd.read_csv(r"D:\IPL-Project--master\PROJECT_FOLDER\datasets\mod_matches.csv")
ipl2.sample(5)

,match_id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
471,829733,2015,Pune,2015-04-18,League,AD Russell,Maharashtra Cricket Association Stadium,Punjab Kings,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,wickets,4.0,156.0,20.0,N,NaN,SD Fry,CK Nandan
23,336005,2008,Jaipur,2008-05-04,League,Sohail Tanvir,Sawai Mansingh Stadium,Rajasthan Royals,Chennai Super Kings,Chennai Super Kings,bat,Rajasthan Royals,wickets,8.0,110.0,20.0,N,NaN,Asad Rauf,AV Jayaprakash
24,336006,2008,Bengaluru,2008-05-05,League,S Sreesanth,M Chinnaswamy Stadium,Royal Challengers Bangalore,Punjab Kings,Punjab Kings,field,Punjab Kings,wickets,6.0,127.0,20.0,N,NaN,SJ Davis,BR Doctrove
620,1082635,2017,Delhi,2017-05-06,League,LMP Simmons,Feroz Shah Kotla,Delhi Capitals,Mumbai Indians,Delhi Capitals,field,Mumbai Indians,runs,146.0,213.0,20.0,N,NaN,Nitin Menon,CK Nandan
735,1178415,2019,Jaipur,2019-04-22,League,RR Pant,Sawai Mansingh Stadium,Rajasthan Royals,Delhi Capitals,Delhi Capitals,field,Delhi Capitals,wickets,6.0,192.0,20.0,N,NaN,A Nand Kishore,S Ravi

## A)Basic API's

### 1) Team Names:
- for teams name I created a dict with all teams name from team1 and team2 column then to get uniques from them converted it to set and then converted it to dict and finnaly to json

In [9]:
def team_name():
    a=set(list(ipl2['team1'])+list(ipl2['team2']))
    dict1={'Team_Name':list(a)}
    return dict1

In [10]:
team_name()

{'Team_Name': ['Kochi Tuskers Kerala',
  'Royal Challengers Bangalore',
  'Rajasthan Royals',
  'Rising Pune Supergiant',
  'Gujarat Titans',
  'Mumbai Indians',
  'Kolkata Knight Riders',
  'Lucknow Super Giants',
  'Chennai Super Kings',
  'Delhi Capitals',
  'Punjab Kings',
  'Sunrisers Hyderabad']}

### 2) Player Names
-  for players I merged both columns named batter and bowler to get list of players

In [12]:
def players():
    a=set(list(ipl1['batter'])+list(ipl1['bowler']))
    players={'Players':list(a)}
    return players

In [13]:
players()

{'Players': ['Sameer Rizvi',
  'P Amarnath',
  'UBT Chand',
  'MP Stoinis',
  'M Markande',
  'VS Yeligati',
  'DNT Zoysa',
  'Mustafizur Rahman',
  'RR Pant',
  'Kamran Khan',
  'NT Ellis',
  'UT Khawaja',
  'S Midhun',
  'DJ Thornely',
  'Mayank Dagar',
  'AS Roy',
  'AR Bawne',
  'MDKJ Perera',
  'AP Dole',
  'SP Jackson',
  'B Chipli',
  'M Klinger',
  'VY Mahesh',
  'SS Shaikh',
  'VRV Singh',
  'NJ Rimmington',
  'P Parameswaran',
  'SA Asnodkar',
  'S Ladda',
  'Shahbaz Ahmed',
  'PK Garg',
  'PH Solanki',
  'SMSM Senanayake',
  'NS Naik',
  'Kumar Kushagra',
  'LH Ferguson',
  'AS Rajpoot',
  'M Ashwin',
  'UT Yadav',
  'AM Nayar',
  'BJ Hodge',
  'Gurnoor Brar',
  'V Kaverappa',
  'D Wiese',
  'Harbhajan Singh',
  'Salman Butt',
  'G Coetzee',
  'Umran Malik',
  'SS Prabhudessai',
  'SS Mundhe',
  'CH Morris',
  'Joginder Sharma',
  'C Sakariya',
  'Navdeep Saini',
  'CJ McKay',
  'P Awana',
  'SD Chitnis',
  'SK Raina',
  'L Ronchi',
  'A Nehra',
  'J Theron',
  'N Jagadeesan',
  'SA Yadav',
  'K Kartikeya',
  'AP Tare',
  'SK Trivedi',
  'PP Ojha',
  'DJ Mitchell',
  'ML Hayden',
  'Sumit Kumar',
  'S Joseph',
  'AC Blizzard',
  'YS Chahal',
  'BR Sharath',
  'Anuj Rawat',
  'KA Pollard',
  'AR Patel',
  'AN Ghosh',
  'BAW Mendis',
  'V Pratap Singh',
  'T Shamsi',
  'B Geeves',
  'T Banton',
  'Akash Deep',
  'S Randiv',
  'KA Jamieson',
  'MN van Wyk',
  'R Ashwin',
  'Naveen-ul-Haq',
  'JE Taylor',
  'JD Ryder',
  'WPUJC Vaas',
  'SB Dubey',
  'M Pathirana',
  'JR Hazlewood',
  'SN Thakur',
  'Kuldeep Yadav',
  'GB Hogg',
  'TS Mills',
  'Abdur Razzak',
  'M Siddharth',
  'RJ Peterson',
  'RA Jadeja',
  'VR Aaron',
  'SV Samson',
  'CA Pujara',
  'KS Bharat',
  'CJ Anderson',
  'DS Kulkarni',
  'LS Livingstone',
  'Arshad Khan',
  'KK Cooper',
  'DB Ravi Teja',
  'RJ Harris',
  'SP Goswami',
  'MS Dhoni',
  'HF Gurney',
  'CV Varun',
  'AS Yadav',
  'LA Carseldine',
  'RS Hangargekar',
  'R Tewatia',
  'S Rana',
  'AU Rashid',
  'SC Kuggeleijn',
  'B Indrajith',
  'PP Shaw',
  'RN ten Doeschate',
  'Washington Sundar',
  'SS Tiwary',
  'NL McCullum',
  'PJ Sangwan',
  'AC Voges',
  'RK Bhui',
  'Anureet Singh',
  'P Simran Singh',
  'UA Birla',
  'PN Mankad',
  'B Sai Sudharsan',
  'KR Sen',
  'GH Vihari',
  'DJG Sammy',
  'MG Neser',
  'Swapnil Singh',
  'Ravi Bishnoi',
  'MM Patel',
  'C Madan',
  'DR Sams',
  'RP Singh',
  'AB Dinda',
  'Gurkeerat Singh',
  'BB Samantray',
  'R Sanjay Yadav',
  'S Narwal',
  'VH Zol',
  'P Ray Barman',
  'DA Warner',
  'DAJ Bracewell',
  'C Green',
  'AB de Villiers',
  'Simarjeet Singh',
  'KH Pandya',
  'Ramandeep Singh',
  'KP Appanna',
  'CK Langeveldt',
  'DJ Willey',
  'Ankit Soni',
  'Bipul Sharma',
  'JPR Scantlebury-Searles',
  'SH Johnson',
  'M Muralitharan',
  'Mandeep Singh',
  'CK Kapugedera',
  'DL Chahar',
  'R Shepherd',
  'Parvez Rasool',
  'K Goel',
  'SL Malinga',
  'D Salunkhe',
  'MJ Santner',
  'BR Dunk',
  'AC Gilchrist',
  'AUK Pathan',
  'Mukesh Choudhary',
  'P Kumar',
  'PP Chawla',
  'S Lamichhane',
  'JA Richardson',
  'AA Kulkarni',
  'JA Morkel',
  'D Ferreira',
  'T Natarajan',
  'JL Denly',
  'Abdul Samad',
  'Akash Singh',
  'AD Mascarenhas',
  'AJ Hosein',
  'KV Sharma',
  'Kartik Tyagi',
  'KK Nair',
  'N Thushara',
  'KJ Abbott',
  'JP Duminy',
  'V Viyaskanth',
  'DJM Short',
  'LRPL Taylor',
  'JW Hastings',
  'J Little',
  'Jaskaran Singh',
  'Abishek Porel',
  'IC Pandey',
  'SM Katich',
  'AJ Turner',
  'Noor Ahmad',
  'RV Patel',
  'Vijaykumar Vyshak',
  'M Theekshana',
  'Arshdeep Singh',
  'FY Fazal',
  'TM Srivastava',
  'CRD Fernando',
  'M Manhas',
  'AA Noffke',
  'A Badoni',
  'S Sreesanth',
  'Saurav Chauhan',
  'DL Vettori',
  'M de Lange',
  'KL Rahul',
  'F Behardien',
  'MJ McClenaghan',
  'V Kohli',
  'KC Sangakkara',
  'JD Unadkat',
  'MK Pandey',
  'S Badree',
  'Rasikh Salam',
  'AS Joseph',
  'Abdul Basith',
  'S Chanderpaul',
  'Yudhvir Singh',
  'K Gowtham',
  'Tilak Varma',
  'JC Buttler',
  'MK Lomror',
  'BMAJ Mendis',
  'RS Sodhi',
  'BJ Haddin',
  'MJ Clarke',
  'RA Tripathi',
  'PBB Rajapaksa',
  'Z Khan',
  'TR Birt',
  'AJ Tye',
  'LR Shukla',
  'V Sehwag',
  'AT Carey',
  'RR Rossouw',
  'J Yadav',
  'Mukesh Kumar',
  'VR Iyer',
  'KD Karthik',
  'AG Murtaza',
  'AP Majumdar',
  'R Ravindra',
  'M Rawat',
  'SM Pollock',
  'SC Ganguly',
  'SD Hope',
  'Tejas Baroka',
  'MP Yadav',
  'MJ Lumb',
  'MR Marsh',
  'X Thalaivan Sargunam',
  'PR Shah',
  'C Nanda',
  'NLTC Perera',
  'Shubman Gill',
  'SB Joshi',
  'JO Holder',
  'SD Lad',
  'JL Pattinson',
  'Arjun Tendulkar',
  'Suyash Sharma',
  'Pankaj Singh',
  'AM Rahane',
  'AN Ahmed',
  'CJ Ferguson',
  'RR Powar',
  'R McLaren',
  'TL Suman',
  'YV Dhull',
  'U Kaul',
  'PVD Chameera',
  'AS Raut',
  'S Dube',
  'Sohail Tanvir',
  'PM Sarvesh Kumar',
  'K Yadav',
  'MF Maharoof',
  'YK Pathan',
  'DR Shorey',
  'Aman Hakim Khan',
  'KB Arun Karthik',
  'NB Singh',
  'LJ Wright',
  'LI Meriwala',
  'A Mishra',
  'A Dananjaya',
  'GC Viljoen',
  'Nithish Kumar Reddy',
  'R Shukla',
  'Azhar Mahmood',
  'Mohammed Siraj',
  'Younis Khan',
  'L Ngidi',
  'AB McDonald',
  'KW Richardson',
  'SS Agarwal',
  'Sandeep Sharma',
  'YA Abdulla',
  'N Saini',
  'SE Rutherford',
  'A Ashish Reddy',
  'BB McCullum',
  'D du Preez',
  'SW Tait',
  'Shashank Singh',
  'Harshit Rana',
  'B Akhil',
  'DG Nalkande',
  'L Wood',
  'LPC Silva',
  'RV Uthappa',
  'R Vinay Kumar',
  'SE Bond',
  'CR Brathwaite',
  'SZ Mulani',
  'S Kaul',
  'AB Agarkar',
  'OA Shah',
  'VVS Laxman',
  'S Badrinath',
  'DR Smith',
  'A Flintoff',
  'RD Chahar',
  'TL Seifert',
  'D Brevis',
  'JC Archer',
  'ND Doshi',
  'SM Harwood',
  'STR Binny',
  'MA Agarwal',
  'MS Gony',
  'A Chandila',
  'M Kartik',
  'Shivam Sharma',
  'RS Bopara',
  'CA Lynn',
  'Basil Thampi',
  'IS Sodhi',
  'OF Smith',
  'BB Sran',
  'Ashutosh Sharma',
  'SO Hetmyer',
  'SK Warne',
  'CJ Jordan',
  'DM Bravo',
  'Abhishek Sharma',
  'S Gopal',
  'P Chopra',
  'CM Gautam',
  'L Ablish',
  'A Chopra',
  'KS Sharma',
  'SR Tendulkar',
  'RJ Quiney',
  'Ankit Sharma',
  'RA Bawa',
  'PD Salt',
  'LB Williams',
  'Naman Dhir',
  'KMA Paul',
  'Mohammad Nabi',
  'JH Kallis',
  'HH Gibbs',
  'AA Kazi',
  'M Vohra',
  'DS Lehmann',
  'J Arunkumar',
  'P Dogra',
  'Shoaib Ahmed',
  'EJG Morgan',
  'TP Sudhindra',
  'RM Patidar',
  'K Rabada',
  'P Dubey',
  'CH Gayle',
  'WA Mota',
  'MG Bracewell',
  'J Suchith',
  'HE van der Dussen',
  'MC Juneja',
  'R Powell',
  'CJ Green',
  'DB Das',
  'DT Patil',
  'Mohit Rathee',
  'Harmeet Singh',
  'SW Billings',
  'Jalaj S Saxena',
  'A Symonds',
  'RS Gavaskar',
  'LMP Simmons',
  'E Lewis',
  'JR Philippe',
  'S Kaushik',
  'SPD Smith',
  'MEK Hussey',
  'B Kumar',
  'AD Nath',
  'O Thomas',
  'SSB Magala',
  'MJ Guptill',
  'RE van der Merwe',
  'AD Russell',
  'MK Tiwary',
  'MC Henriques',
  'J Syed Mohammad',
  'ER Dwivedi',
  'SA Abbott',
  'PSP Handscomb',
  'B Laughlin',
  'T Thushara',
  'NV Ojha',
  'A Nel',
  'G Gambhir',
  'R Sai Kishore',
  'LA Pomersbach',
  'R Sharma',
  'BW Hilfenhaus',
  'Shoaib Akhtar',
  'JJ Roy',
  'N Rana',
  'Shakib Al Hasan',
  'CA Ingram',
  'Arshad Khan (2)',
  'BCJ Cutting',
  'C de Grandhomme',
  'JDP Oram',
  'AD Mathews',
  'R Parag',
  'R Rampaul',
  'GJ Maxwell',
  'DJ Harris',
  'KM Asif',
  'Gagandeep Singh',
  'Sunny Gupta',
  'MM Sharma',
  'TG Southee',
  'SN Khan',
  'OC McCoy',
  'GS Sandhu',
  'N Burger',
  'Mashrafe Mortaza',
  'H Das',
  'DJ Bravo',
  'I Udana',
  'DH Yagnik',
  'JJ Bumrah',
  'Misbah-ul-Haq',
  'JP Faulkner',
  'SP Narine',
  'AF Milne',
  'T Kohler-Cadmore',
  'Rashid Khan',
  'Avesh Khan',
  'AG Paunikar',
  'TD Paine',
  'C Munro',
  'IR Jaggi',
  'Sikandar Raza',
  'SS Sarkar',
  'KM Jadhav',
  'Shoaib Malik',
  'R Sathish',
  'P Suyal',
  'Yash Thakur',
  'Yuvraj Singh',
  'BE Hendricks',
  'D Pretorius',
  'MD Shanaka',
  'RR Sarwan',
  'R Bishnoi',
  'Ishan Kishan',
  'Yashpal Singh',
  'JEC Franklin',
  'MM Ali',
  'S Sriram',
  'DJ Hussey',
  'JJ van der Wath',
  'HH Pandya',
  'T Henderson',
  'S Sandeep Warrier',
  'A Uniyal',
  'Imran Tahir',
  'S Anirudha',
  'RK Singh',
  'Anand Rajan',
  'DA Miller',
  'GD Phillips',
  'MJ Suthar',
  'SM Boland',
  'Mujeeb Ur Rahman',
  'B Sumanth',
  'RG More',
  'Monu Kumar',
  'RP Meredith',
  'T Stubbs',
  'GJ Bailey',
  'MS Wade',
  'HV Patel',
  'D Jansen',
  'F du Plessis',
  'MJ Henry',
  'YBK Jaiswal',
  'R Ninan',
  'DT Christian',
  'SE Marsh',
  'MA Starc',
  'KP Pietersen',
  'M Prasidh Krishna',
  'R Goyal',
  'S Aravind',
  'B Lee',
  'Mohammad Asif',
  'JE Root',
  'S Tyagi',
  'C Ganapathy',
  'P Sahu',
  'FA Allen',
  'K Santokie',
  'D Kalyankrishna',
  'GHS Garton',
  'SJ Srivastava',
  'JDS Neesham',
  'Shivam Singh',
  'GD McGrath',
  'RA Shaikh',
  'N Wadhera',
  'W Jaffer',
  'GC Smith',
  'A Zampa',
  'CR Woakes',
  'PWH de Silva',
  'R Dravid',
  'PV Tambe',
  'BJ Rohrer',
  'YV Takawale',
  'KL Nagarkoti',
  'Umar Gul',
  'TM Head',
  'SB Bangar',
  'M Shahrukh Khan',
  'KK Ahmed',
  'RR Raje',
  'SR Watson',
  'A Mukund',
  'MD Mishra',
  'DE Bollinger',
  'RV Gomez',
  'MW Short',
  'Y Nagar',
  'WG Jacks',
  'RJW Topley',
  'A Singh',
  'NA Saini',
  'V Shankar',
  'IK Pathan',
  'MN Samuels',
  'WP Saha',
  'A Nortje',
  'SB Jakati',
  'DJ Muthuswami',
  'Sunny Singh',
  'Azmatullah Omarzai',
  'KAJ Roach',
  'JM Sharma',
  'Fazalhaq Farooqi',
  'Lalit Yadav',
  'KA Maharaj',
  'DJ Jacobs',
  'PA Reddy',
  'LE Plunkett',
  'WD Parnell',
  'AC Thomas',
  'M Kaif',
  'PD Collingwood',
  'MA Khote',
  'A Choudhary',
  'NK Patel',
  'Harpreet Singh',
  'TA Boult',
  'Shahid Afridi',
  'Y Prithvi Raj',
  'Y Venugopal Rao',
  'S Dhawan',
  'JP Behrendorff',
  'JR Hopes',
  'Mohammad Hafeez',
  'Dhruv Jurel',
  'AA Jhunjhunwala',
  'CJ Dala',
  'RJ Gleeson',
  'L Balaji',
  'SS Cottrell',
  'AB Barath',
  'AM Salvi',
  'H Sharma',
  'AJ Finch',
  'SB Styris',
  'KC Cariappa',
  'A Mithun',
  'SS Iyer',
  'MA Wood',
  'A Manohar',
  'KMDN Kulasekara',
  'CL White',
  'Mohsin Khan',
  'FH Edwards',
  'PA Patel',
  'S Vidyut',
  'S Nadeem',
  'RG Sharma',
  'A Kumble',
  'VS Malik',
  'RR Bhatkal',
  'SB Wagh',
  'MG Johnson',
  'PJ Cummins',
  'P Prasanth',
  'IC Porel',
  'Mohammad Ashraful',
  'Vishnu Vinod',
  'JM Kemp',
  'AA Chavan',
  'AD Hales',
  'BA Bhatt',
  'RE Levi',
  'Y Gnaneswara Rao',
  'BA Stokes',
  'DR Martyn',
  'TH David',
  'S Sohal',
  'MS Bisla',
  'Q de Kock',
  'RT Ponting',
  'DP Conway',
  'NM Coulter-Nile',
  'Anmolpreet Singh',
  'AT Rayudu',
  'Gulbadin Naib',
  'M Jansen',
  'MV Boucher',
  'VG Arora',
  'K Khejroliya',
  'M Ntini',
  'I Sharma',
  'DJ Hooda',
  'DW Steyn',
  'K Upadhyay',
  'RR Bose',
  'KR Mayers',
  'J Fraser-McGurk',
  'M Vijay',
  'N Pooran',
  'A Kamboj',
  'KS Williamson',
  'Akash Madhwal',
  'B Stanlake',
  'D Padikkal',
  'Kamran Akmal',
  'HC Brook',
  'HM Amla',
  'TU Deshpande',
  'Mohammed Shami',
  'SM Curran',
  'Sanvir Singh',
  'Iqbal Abdulla',
  'DPMD Jayawardene',
  'HR Shokeen',
  'T Taibu',
  'DP Vijaykumar',
  'PC Valthaty',
  'NJ Maddinson',
  'M Morkel',
  'Vivrant Sharma',
  'Yash Dayal',
  'DJ Malan',
  'KT Maphaka',
  'RW Price',
  'Karanveer Singh',
  'A Raghuvanshi',
  'Shivam Mavi',
  'T Kohli',
  'SP Fleming',
  'Anirudh Singh',
  'Virat Singh',
  'AK Markram',
  'Rahmanullah Gurbaz',
  'JM Bairstow',
  'Harpreet Brar',
  'TK Curran',
  'R Dhawan',
  'ST Jayasuriya',
  'MB Parmar',
  'R Bhatia',
  'Sachin Baby',
  'I Malhotra',
  'RD Gaikwad',
  'GR Napier',
  'DP Nannes',
  'TM Dilshan',
  'Tanush Kotian',
  'H Klaasen',
  'AA Bilakhia',
  'Atharva Taide',
  'Liton Das',
  'J Botha',
  'AL Menaria',
  'P Negi',
  'A Tomar']}

## B) Match API's

### 1) match summary

- here we fetch match summary by using teams name and date when they played the match taking these things as input we can give summary of corresponding match

In [17]:
ipl2.columns

Index(['match_id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2'],
      dtype='object')

In [18]:
def match_summary(team1, team2, date):
    # fetching match details with respective data
    data = ipl2[(ipl2['team1'] == team1) & (ipl2['team2'] == team2) & (ipl2['date'] == date)]

    if not data.empty:  # Check if data is not empty to avoid errors
        match = {
            'match_id': data['match_id'].iloc[0],
            'team1': data['team1'].iloc[0],
            'team2': data['team2'].iloc[0],
            'season': data['season'].iloc[0],
            'date': str(data['date'].iloc[0]),
            'city': data['city'].iloc[0],
            'venue': data['venue'].iloc[0],
            'toss_winner': data['toss_winner'].iloc[0],
            'toss_decision': data['toss_decision'].iloc[0],
            'winner': data['winner'].iloc[0],
            'result_margin': data['result_margin'].iloc[0],
            'target_runs': data['target_runs'].iloc[0]
        } # iloc is used to avoid index number
        return (match)
    else:
        return {"error": "No match found with the given details."}

In [19]:
output=match_summary('Royal Challengers Bangalore','Punjab Kings','2008-05-05')

In [20]:
ipl2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   match_id         1095 non-null   int64
 1   season           1095 non-null   int64
 2   city             1090 non-null   object
 3   date             1095 non-null   object
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: float64(3), int64(2), object(15)
memory usage: 171.2+ KB

In [21]:
output

{'match_id': 336006,
 'team1': 'Royal Challengers Bangalore',
 'team2': 'Punjab Kings',
 'season': 2008,
 'date': '2008-05-05',
 'city': 'Bengaluru',
 'venue': 'M Chinnaswamy Stadium',
 'toss_winner': 'Punjab Kings',
 'toss_decision': 'field',
 'winner': 'Punjab Kings',
 'result_margin': 6.0,
 'target_runs': 127.0}

In [22]:
ipl2[(ipl2['team1']== 'Royal Challengers Bangalore')&(ipl2['team2']=='Kings XI Punjab')]

Empty DataFrame
Columns: [match_id, season, city, date, match_type, player_of_match, venue, team1, team2, toss_winner, toss_decision, winner, result, result_margin, target_runs, target_overs, super_over, method, umpire1, umpire2]
Index: []

In [23]:
ipl2[(ipl2['team1'] == 'Royal Challengers Bangalore') & (ipl2['team2'] == 'Punjab Kings')]

,match_id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
24,336006,2008,Bengaluru,2008-05-05,League,S Sreesanth,M Chinnaswamy Stadium,Royal Challengers Bangalore,Punjab Kings,Punjab Kings,field,Punjab Kings,wickets,6.0,127.0,20.0,N,NaN,SJ Davis,BR Doctrove
67,392191,2009,Durban,2009-04-24,League,RS Bopara,Kingsmead,Royal Challengers Bangalore,Punjab Kings,Royal Challengers Bangalore,bat,Punjab Kings,wickets,7.0,169.0,20.0,N,NaN,BR Doctrove,TH Wijewardene
79,392204,2009,Durban,2009-05-01,League,Yuvraj Singh,Kingsmead,Royal Challengers Bangalore,Punjab Kings,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,runs,8.0,146.0,20.0,N,NaN,HDPK Dharmasena,S Ravi
121,419112,2010,Bengaluru,2010-03-16,League,JH Kallis,M Chinnaswamy Stadium,Royal Challengers Bangalore,Punjab Kings,Punjab Kings,bat,Royal Challengers Bangalore,wickets,8.0,204.0,20.0,N,NaN,S Das,DJ Harper
220,501244,2011,Bengaluru,2011-05-06,League,CH Gayle,M Chinnaswamy Stadium,Royal Challengers Bangalore,Punjab Kings,Punjab Kings,field,Royal Challengers Bangalore,runs,85.0,206.0,20.0,N,NaN,Aleem Dar,RB Tiffin
289,548350,2012,Bengaluru,2012-05-02,League,Azhar Mahmood,M Chinnaswamy Stadium,Royal Challengers Bangalore,Punjab Kings,Punjab Kings,field,Punjab Kings,wickets,4.0,159.0,20.0,N,NaN,BF Bowden,C Shamshuddin
384,598045,2013,Bengaluru,2013-05-14,League,AC Gilchrist,M Chinnaswamy Stadium,Royal Challengers Bangalore,Punjab Kings,Punjab Kings,field,Punjab Kings,wickets,7.0,175.0,20.0,N,NaN,HDPK Dharmasena,S Ravi
428,733991,2014,Bengaluru,2014-05-09,League,Sandeep Sharma,M Chinnaswamy Stadium,Royal Challengers Bangalore,Punjab Kings,Royal Challengers Bangalore,field,Punjab Kings,runs,32.0,199.0,20.0,N,NaN,S Ravi,K Srinath
496,829785,2015,Bengaluru,2015-05-06,League,CH Gayle,M Chinnaswamy Stadium,Royal Challengers Bangalore,Punjab Kings,Punjab Kings,field,Royal Challengers Bangalore,runs,138.0,227.0,20.0,N,NaN,RK Illingworth,VA Kulkarni
566,980999,2016,Bengaluru,2016-05-18,League,V Kohli,M Chinnaswamy Stadium,Royal Challengers Bangalore,Punjab Kings,Punjab Kings,field,Royal Challengers Bangalore,runs,82.0,203.0,14.0,N,D/L,KN Ananthapadmanabhan,M Erasmus
618,1082633,2017,Bengaluru,2017-05-05,League,Sandeep Sharma,M Chinnaswamy Stadium,Royal Challengers Bangalore,Punjab Kings,Royal Challengers Bangalore,field,Punjab Kings,runs,19.0,139.0,20.0,N,NaN,CB Gaffaney,C Shamshuddin
737,1178417,2019,Bengaluru,2019-04-24,League,AB de Villiers,M Chinnaswamy Stadium,Royal Challengers Bangalore,Punjab Kings,Punjab Kings,field,Royal Challengers Bangalore,runs,17.0,203.0,20.0,N,NaN,BNJ Oxenford,C Shamshuddin
786,1216531,2020,Sharjah,2020-10-15,League,KL Rahul,Sharjah Cricket Stadium,Royal Challengers Bangalore,Punjab Kings,Royal Challengers Bangalore,bat,Punjab Kings,wickets,8.0,172.0,20.0,N,NaN,KN Ananthapadmanabhan,C Shamshuddin
863,1254090,2021,Sharjah,2021-10-03,League,GJ Maxwell,Sharjah Cricket Stadium,Royal Challengers Bangalore,Punjab Kings,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,runs,6.0,165.0,20.0,N,NaN,KN Ananthapadmanabhan,RK Illingworth
878,1304049,2022,Mumbai,2022-03-27,League,OF Smith,Dr DY Patil Sports Academy,Royal Challengers Bangalore,Punjab Kings,Punjab Kings,field,Punjab Kings,wickets,5.0,206.0,20.0,N,NaN,Nitin Menon,YC Barde
976,1359501,2023,Mohali,2023-04-20,League,Mohammed Siraj,Punjab Cricket Association IS Bindra Stadium,Royal Challengers Bangalore,Punjab Kings,Punjab Kings,field,Royal Challengers Bangalore,runs,24.0,175.0,20.0,N,NaN,AK Chaudhary,GR Sadashiv Iyer
1081,1426296,2024,Dharamshala,2024-05-09,League,V Kohli,Himachal Pradesh Cricket Association Stadium,Royal Challengers Bangalore,Punjab Kings,Punjab Kings,field,Royal Challengers Bangalore,runs,60.0,242.0,20.0,N,NaN,Nitin Menon,HAS Khalid

### 2) match details

- here we will display ball-by-ball details of respective match

In [26]:
ipl1.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs',
       'total_runs', 'extras_type', 'is_wicket', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [27]:
def match_details(team1,team2,date):
    """to get respective match details we compare find the date in second dataset for match id 
    and search the data in 1st dataset cause ipl1 does not have date column""" 
    id=ipl2[(ipl2['team1'] == team1) & (ipl2['team2'] == team2) & (ipl2['date'] == date)]['match_id']
    if not id.empty:
        id=id.iloc[0]
        match_detail=ipl1[ipl1['match_id']==id] # searched respective match in ipl1
        return json.loads(match_detail.to_json(orient='records',index=False)) # else return result, orientation removes index
    else:
        return {'error':'please check whether the details are correct'} #if data not matches

In [28]:
match_details('Royal Challengers Bangalore','Punjab Kings','2016-05-18')

[{'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 0,
  'ball': 1,
  'batter': 'CH Gayle',
  'bowler': 'Sandeep Sharma',
  'non_striker': 'V Kohli',
  'batsman_runs': 0,
  'extra_runs': 0,
  'total_runs': 0,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 0,
  'ball': 2,
  'batter': 'CH Gayle',
  'bowler': 'Sandeep Sharma',
  'non_striker': 'V Kohli',
  'batsman_runs': 0,
  'extra_runs': 0,
  'total_runs': 0,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 0,
  'ball': 3,
  'batter': 'CH Gayle',
  'bowler': 'Sandeep Sharma',
  'non_striker': 'V Kohli',
  'batsman_runs': 0,
  'extra_runs': 0,
  'total_runs': 0,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 0,
  'ball': 4,
  'batter': 'CH Gayle',
  'bowler': 'Sandeep Sharma',
  'non_striker': 'V Kohli',
  'batsman_runs': 0,
  'extra_runs': 0,
  'total_runs': 0,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 0,
  'ball': 5,
  'batter': 'CH Gayle',
  'bowler': 'Sandeep Sharma',
  'non_striker': 'V Kohli',
  'batsman_runs': 1,
  'extra_runs': 0,
  'total_runs': 1,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 0,
  'ball': 6,
  'batter': 'V Kohli',
  'bowler': 'Sandeep Sharma',
  'non_striker': 'CH Gayle',
  'batsman_runs': 4,
  'extra_runs': 0,
  'total_runs': 4,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 1,
  'ball': 1,
  'batter': 'CH Gayle',
  'bowler': 'MM Sharma',
  'non_striker': 'V Kohli',
  'batsman_runs': 1,
  'extra_runs': 0,
  'total_runs': 1,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 1,
  'ball': 2,
  'batter': 'V Kohli',
  'bowler': 'MM Sharma',
  'non_striker': 'CH Gayle',
  'batsman_runs': 0,
  'extra_runs': 0,
  'total_runs': 0,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 1,
  'ball': 3,
  'batter': 'V Kohli',
  'bowler': 'MM Sharma',
  'non_striker': 'CH Gayle',
  'batsman_runs': 1,
  'extra_runs': 0,
  'total_runs': 1,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 1,
  'ball': 4,
  'batter': 'CH Gayle',
  'bowler': 'MM Sharma',
  'non_striker': 'V Kohli',
  'batsman_runs': 0,
  'extra_runs': 0,
  'total_runs': 0,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 1,
  'ball': 5,
  'batter': 'CH Gayle',
  'bowler': 'MM Sharma',
  'non_striker': 'V Kohli',
  'batsman_runs': 4,
  'extra_runs': 0,
  'total_runs': 4,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 1,
  'ball': 6,
  'batter': 'CH Gayle',
  'bowler': 'MM Sharma',
  'non_striker': 'V Kohli',
  'batsman_runs': 0,
  'extra_runs': 0,
  'total_runs': 0,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 2,
  'ball': 1,
  'batter': 'V Kohli',
  'bowler': 'Sandeep Sharma',
  'non_striker': 'CH Gayle',
  'batsman_runs': 0,
  'extra_runs': 0,
  'total_runs': 0,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 2,
  'ball': 2,
  'batter': 'V Kohli',
  'bowler': 'Sandeep Sharma',
  'non_striker': 'CH Gayle',
  'batsman_runs': 1,
  'extra_runs': 0,
  'total_runs': 1,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 2,
  'ball': 3,
  'batter': 'CH Gayle',
  'bowler': 'Sandeep Sharma',
  'non_striker': 'V Kohli',
  'batsman_runs': 0,
  'extra_runs': 0,
  'total_runs': 0,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 2,
  'ball': 4,
  'batter': 'CH Gayle',
  'bowler': 'Sandeep Sharma',
  'non_striker': 'V Kohli',
  'batsman_runs': 1,
  'extra_runs': 0,
  'total_runs': 1,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 2,
  'ball': 5,
  'batter': 'V Kohli',
  'bowler': 'Sandeep Sharma',
  'non_striker': 'CH Gayle',
  'batsman_runs': 4,
  'extra_runs': 0,
  'total_runs': 4,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 2,
  'ball': 6,
  'batter': 'V Kohli',
  'bowler': 'Sandeep Sharma',
  'non_striker': 'CH Gayle',
  'batsman_runs': 0,
  'extra_runs': 0,
  'total_runs': 0,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 3,
  'ball': 1,
  'batter': 'CH Gayle',
  'bowler': 'KJ Abbott',
  'non_striker': 'V Kohli',
  'batsman_runs': 0,
  'extra_runs': 1,
  'total_runs': 1,
  'extras_type': 'wides',
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 3,
  'ball': 2,
  'batter': 'CH Gayle',
  'bowler': 'KJ Abbott',
  'non_striker': 'V Kohli',
  'batsman_runs': 6,
  'extra_runs': 0,
  'total_runs': 6,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 3,
  'ball': 3,
  'batter': 'CH Gayle',
  'bowler': 'KJ Abbott',
  'non_striker': 'V Kohli',
  'batsman_runs': 6,
  'extra_runs': 0,
  'total_runs': 6,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 3,
  'ball': 4,
  'batter': 'CH Gayle',
  'bowler': 'KJ Abbott',
  'non_striker': 'V Kohli',
  'batsman_runs': 4,
  'extra_runs': 0,
  'total_runs': 4,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 3,
  'ball': 5,
  'batter': 'CH Gayle',
  'bowler': 'KJ Abbott',
  'non_striker': 'V Kohli',
  'batsman_runs': 1,
  'extra_runs': 0,
  'total_runs': 1,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 3,
  'ball': 6,
  'batter': 'V Kohli',
  'bowler': 'KJ Abbott',
  'non_striker': 'CH Gayle',
  'batsman_runs': 0,
  'extra_runs': 0,
  'total_runs': 0,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 3,
  'ball': 7,
  'batter': 'V Kohli',
  'bowler': 'KJ Abbott',
  'non_striker': 'CH Gayle',
  'batsman_runs': 0,
  'extra_runs': 0,
  'total_runs': 0,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 4,
  'ball': 1,
  'batter': 'CH Gayle',
  'bowler': 'KC Cariappa',
  'non_striker': 'V Kohli',
  'batsman_runs': 6,
  'extra_runs': 0,
  'total_runs': 6,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 4,
  'ball': 2,
  'batter': 'CH Gayle',
  'bowler': 'KC Cariappa',
  'non_striker': 'V Kohli',
  'batsman_runs': 4,
  'extra_runs': 0,
  'total_runs': 4,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 4,
  'ball': 3,
  'batter': 'CH Gayle',
  'bowler': 'KC Cariappa',
  'non_striker': 'V Kohli',
  'batsman_runs': 1,
  'extra_runs': 0,
  'total_runs': 1,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 4,
  'ball': 4,
  'batter': 'V Kohli',
  'bowler': 'KC Cariappa',
  'non_striker': 'CH Gayle',
  'batsman_runs': 6,
  'extra_runs': 0,
  'total_runs': 6,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 4,
  'ball': 5,
  'batter': 'V Kohli',
  'bowler': 'KC Cariappa',
  'non_striker': 'CH Gayle',
  'batsman_runs': 1,
  'extra_runs': 0,
  'total_runs': 1,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 4,
  'ball': 6,
  'batter': 'CH Gayle',
  'bowler': 'KC Cariappa',
  'non_striker': 'V Kohli',
  'batsman_runs': 0,
  'extra_runs': 0,
  'total_runs': 0,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 5,
  'ball': 1,
  'batter': 'V Kohli',
  'bowler': 'AR Patel',
  'non_striker': 'CH Gayle',
  'batsman_runs': 0,
  'extra_runs': 0,
  'total_runs': 0,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 5,
  'ball': 2,
  'batter': 'V Kohli',
  'bowler': 'AR Patel',
  'non_striker': 'CH Gayle',
  'batsman_runs': 0,
  'extra_runs': 0,
  'total_runs': 0,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 5,
  'ball': 3,
  'batter': 'V Kohli',
  'bowler': 'AR Patel',
  'non_striker': 'CH Gayle',
  'batsman_runs': 1,
  'extra_runs': 0,
  'total_runs': 1,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 5,
  'ball': 4,
  'batter': 'CH Gayle',
  'bowler': 'AR Patel',
  'non_striker': 'V Kohli',
  'batsman_runs': 1,
  'extra_runs': 0,
  'total_runs': 1,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 5,
  'ball': 5,
  'batter': 'V Kohli',
  'bowler': 'AR Patel',
  'non_striker': 'CH Gayle',
  'batsman_runs': 4,
  'extra_runs': 0,
  'total_runs': 4,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 5,
  'ball': 6,
  'batter': 'V Kohli',
  'bowler': 'AR Patel',
  'non_striker': 'CH Gayle',
  'batsman_runs': 4,
  'extra_runs': 0,
  'total_runs': 4,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 6,
  'ball': 1,
  'batter': 'CH Gayle',
  'bowler': 'KC Cariappa',
  'non_striker': 'V Kohli',
  'batsman_runs': 1,
  'extra_runs': 0,
  'total_runs': 1,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 6,
  'ball': 2,
  'batter': 'V Kohli',
  'bowler': 'KC Cariappa',
  'non_striker': 'CH Gayle',
  'batsman_runs': 4,
  'extra_runs': 0,
  'total_runs': 4,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 6,
  'ball': 3,
  'batter': 'V Kohli',
  'bowler': 'KC Cariappa',
  'non_striker': 'CH Gayle',
  'batsman_runs': 0,
  'extra_runs': 0,
  'total_runs': 0,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 6,
  'ball': 4,
  'batter': 'V Kohli',
  'bowler': 'KC Cariappa',
  'non_striker': 'CH Gayle',
  'batsman_runs': 0,
  'extra_runs': 0,
  'total_runs': 0,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 6,
  'ball': 5,
  'batter': 'V Kohli',
  'bowler': 'KC Cariappa',
  'non_striker': 'CH Gayle',
  'batsman_runs': 6,
  'extra_runs': 1,
  'total_runs': 7,
  'extras_type': 'noballs',
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 6,
  'ball': 6,
  'batter': 'V Kohli',
  'bowler': 'KC Cariappa',
  'non_striker': 'CH Gayle',
  'batsman_runs': 6,
  'extra_runs': 0,
  'total_runs': 6,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 6,
  'ball': 7,
  'batter': 'V Kohli',
  'bowler': 'KC Cariappa',
  'non_striker': 'CH Gayle',
  'batsman_runs': 1,
  'extra_runs': 0,
  'total_runs': 1,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 7,
  'ball': 1,
  'batter': 'V Kohli',
  'bowler': 'KJ Abbott',
  'non_striker': 'CH Gayle',
  'batsman_runs': 1,
  'extra_runs': 0,
  'total_runs': 1,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 7,
  'ball': 2,
  'batter': 'CH Gayle',
  'bowler': 'KJ Abbott',
  'non_striker': 'V Kohli',
  'batsman_runs': 1,
  'extra_runs': 0,
  'total_runs': 1,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 7,
  'ball': 3,
  'batter': 'V Kohli',
  'bowler': 'KJ Abbott',
  'non_striker': 'CH Gayle',
  'batsman_runs': 0,
  'extra_runs': 0,
  'total_runs': 0,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 7,
  'ball': 4,
  'batter': 'V Kohli',
  'bowler': 'KJ Abbott',
  'non_striker': 'CH Gayle',
  'batsman_runs': 4,
  'extra_runs': 0,
  'total_runs': 4,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 7,
  'ball': 5,
  'batter': 'V Kohli',
  'bowler': 'KJ Abbott',
  'non_striker': 'CH Gayle',
  'batsman_runs': 1,
  'extra_runs': 0,
  'total_runs': 1,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,
  'batting_team': 'Royal Challengers Bangalore',
  'bowling_team': 'Punjab Kings',
  'over': 7,
  'ball': 6,
  'batter': 'CH Gayle',
  'bowler': 'KJ Abbott',
  'non_striker': 'V Kohli',
  'batsman_runs': 4,
  'extra_runs': 0,
  'total_runs': 4,
  'extras_type': None,
  'is_wicket': 0,
  'player_dismissed': None,
  'dismissal_kind': None,
  'fielder': None},
 {'match_id': 980999,
  'inning': 1,

In [29]:
ipl2[(ipl2['team1'] == 'Royal Challengers Bangalore') & (ipl2['team2'] == 'Punjab Kings') & (ipl2['date'] == '2016-05-18')]['match_id'].iloc[0]

980999

### 3) Season Matches

- here by taking input as season we will display every match details of that season like teams, winner, result, resultmargin, venue,man of the match,date

In [32]:
"""
    this function firstly checks whether we have data of respective season or not if yes then return the records else return error
"""
def season_record(season):
    seasons_played=ipl2['season'].unique()
    if season in seasons_played:
        records=ipl2[ipl2['season']==season]
        # json.loads is used to convert inner string value to json
        response=json.loads(records.to_json(orient='records',index=False))
        return response
    else:
        return {'error':"Sorry we don't have data of this season"}

In [33]:
season_record(2011)

[{'match_id': 501198,
  'season': 2011,
  'city': 'Chennai',
  'date': '2011-04-08',
  'match_type': 'League',
  'player_of_match': 'S Anirudha',
  'venue': 'MA Chidambaram Stadium',
  'team1': 'Chennai Super Kings',
  'team2': 'Kolkata Knight Riders',
  'toss_winner': 'Chennai Super Kings',
  'toss_decision': 'bat',
  'winner': 'Chennai Super Kings',
  'result': 'runs',
  'result_margin': 2.0,
  'target_runs': 154.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'BR Doctrove',
  'umpire2': 'PR Reiffel'},
 {'match_id': 501199,
  'season': 2011,
  'city': 'Hyderabad',
  'date': '2011-04-09',
  'match_type': 'League',
  'player_of_match': 'SK Trivedi',
  'venue': 'Rajiv Gandhi International Stadium',
  'team1': 'Sunrisers Hyderabad',
  'team2': 'Rajasthan Royals',
  'toss_winner': 'Rajasthan Royals',
  'toss_decision': 'field',
  'winner': 'Rajasthan Royals',
  'result': 'wickets',
  'result_margin': 8.0,
  'target_runs': 138.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'RE Koertzen',
  'umpire2': 'SK Tarapore'},
 {'match_id': 501200,
  'season': 2011,
  'city': None,
  'date': '2011-04-09',
  'match_type': 'League',
  'player_of_match': 'AB de Villiers',
  'venue': 'Nehru Stadium',
  'team1': 'Kochi Tuskers Kerala',
  'team2': 'Royal Challengers Bangalore',
  'toss_winner': 'Kochi Tuskers Kerala',
  'toss_decision': 'bat',
  'winner': 'Royal Challengers Bangalore',
  'result': 'wickets',
  'result_margin': 6.0,
  'target_runs': 162.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'HDPK Dharmasena',
  'umpire2': 'K Hariharan'},
 {'match_id': 501201,
  'season': 2011,
  'city': 'Delhi',
  'date': '2011-04-10',
  'match_type': 'League',
  'player_of_match': 'SL Malinga',
  'venue': 'Feroz Shah Kotla',
  'team1': 'Delhi Capitals',
  'team2': 'Mumbai Indians',
  'toss_winner': 'Delhi Capitals',
  'toss_decision': 'bat',
  'winner': 'Mumbai Indians',
  'result': 'wickets',
  'result_margin': 8.0,
  'target_runs': 96.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'AM Saheba',
  'umpire2': 'RB Tiffin'},
 {'match_id': 501202,
  'season': 2011,
  'city': 'Mumbai',
  'date': '2011-04-10',
  'match_type': 'League',
  'player_of_match': 'SB Wagh',
  'venue': 'Dr DY Patil Sports Academy',
  'team1': 'Rising Pune Supergiant',
  'team2': 'Punjab Kings',
  'toss_winner': 'Punjab Kings',
  'toss_decision': 'bat',
  'winner': 'Rising Pune Supergiant',
  'result': 'wickets',
  'result_margin': 7.0,
  'target_runs': 113.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'BR Doctrove',
  'umpire2': 'PR Reiffel'},
 {'match_id': 501203,
  'season': 2011,
  'city': 'Kolkata',
  'date': '2011-04-11',
  'match_type': 'League',
  'player_of_match': 'JH Kallis',
  'venue': 'Eden Gardens',
  'team1': 'Kolkata Knight Riders',
  'team2': 'Sunrisers Hyderabad',
  'toss_winner': 'Kolkata Knight Riders',
  'toss_decision': 'bat',
  'winner': 'Kolkata Knight Riders',
  'result': 'runs',
  'result_margin': 9.0,
  'target_runs': 164.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'RE Koertzen',
  'umpire2': 'SK Tarapore'},
 {'match_id': 501204,
  'season': 2011,
  'city': 'Jaipur',
  'date': '2011-04-12',
  'match_type': 'League',
  'player_of_match': 'SK Warne',
  'venue': 'Sawai Mansingh Stadium',
  'team1': 'Rajasthan Royals',
  'team2': 'Delhi Capitals',
  'toss_winner': 'Delhi Capitals',
  'toss_decision': 'bat',
  'winner': 'Rajasthan Royals',
  'result': 'wickets',
  'result_margin': 6.0,
  'target_runs': 152.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'Aleem Dar',
  'umpire2': 'RB Tiffin'},
 {'match_id': 501205,
  'season': 2011,
  'city': 'Bengaluru',
  'date': '2011-04-12',
  'match_type': 'League',
  'player_of_match': 'SR Tendulkar',
  'venue': 'M Chinnaswamy Stadium',
  'team1': 'Royal Challengers Bangalore',
  'team2': 'Mumbai Indians',
  'toss_winner': 'Mumbai Indians',
  'toss_decision': 'field',
  'winner': 'Mumbai Indians',
  'result': 'wickets',
  'result_margin': 9.0,
  'target_runs': 141.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'HDPK Dharmasena',
  'umpire2': 'AL Hill'},
 {'match_id': 501206,
  'season': 2011,
  'city': 'Mohali',
  'date': '2011-04-13',
  'match_type': 'League',
  'player_of_match': 'PC Valthaty',
  'venue': 'Punjab Cricket Association IS Bindra Stadium',
  'team1': 'Punjab Kings',
  'team2': 'Chennai Super Kings',
  'toss_winner': 'Punjab Kings',
  'toss_decision': 'field',
  'winner': 'Punjab Kings',
  'result': 'wickets',
  'result_margin': 6.0,
  'target_runs': 189.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'Asad Rauf',
  'umpire2': 'SL Shastri'},
 {'match_id': 501207,
  'season': 2011,
  'city': 'Mumbai',
  'date': '2011-04-13',
  'match_type': 'League',
  'player_of_match': 'MD Mishra',
  'venue': 'Dr DY Patil Sports Academy',
  'team1': 'Rising Pune Supergiant',
  'team2': 'Kochi Tuskers Kerala',
  'toss_winner': 'Kochi Tuskers Kerala',
  'toss_decision': 'bat',
  'winner': 'Rising Pune Supergiant',
  'result': 'wickets',
  'result_margin': 4.0,
  'target_runs': 149.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'S Asnani',
  'umpire2': 'PR Reiffel'},
 {'match_id': 501208,
  'season': 2011,
  'city': 'Hyderabad',
  'date': '2011-04-14',
  'match_type': 'League',
  'player_of_match': 'DW Steyn',
  'venue': 'Rajiv Gandhi International Stadium',
  'team1': 'Sunrisers Hyderabad',
  'team2': 'Royal Challengers Bangalore',
  'toss_winner': 'Royal Challengers Bangalore',
  'toss_decision': 'field',
  'winner': 'Sunrisers Hyderabad',
  'result': 'runs',
  'result_margin': 33.0,
  'target_runs': 176.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'RE Koertzen',
  'umpire2': 'S Ravi'},
 {'match_id': 501209,
  'season': 2011,
  'city': 'Jaipur',
  'date': '2011-04-15',
  'match_type': 'League',
  'player_of_match': 'G Gambhir',
  'venue': 'Sawai Mansingh Stadium',
  'team1': 'Rajasthan Royals',
  'team2': 'Kolkata Knight Riders',
  'toss_winner': 'Kolkata Knight Riders',
  'toss_decision': 'field',
  'winner': 'Kolkata Knight Riders',
  'result': 'wickets',
  'result_margin': 9.0,
  'target_runs': 160.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'Aleem Dar',
  'umpire2': 'SS Hazare'},
 {'match_id': 501210,
  'season': 2011,
  'city': 'Mumbai',
  'date': '2011-04-15',
  'match_type': 'League',
  'player_of_match': 'BB McCullum',
  'venue': 'Wankhede Stadium',
  'team1': 'Mumbai Indians',
  'team2': 'Kochi Tuskers Kerala',
  'toss_winner': 'Kochi Tuskers Kerala',
  'toss_decision': 'field',
  'winner': 'Kochi Tuskers Kerala',
  'result': 'wickets',
  'result_margin': 8.0,
  'target_runs': 183.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'BR Doctrove',
  'umpire2': 'PR Reiffel'},
 {'match_id': 501211,
  'season': 2011,
  'city': 'Chennai',
  'date': '2011-04-16',
  'match_type': 'League',
  'player_of_match': 'MEK Hussey',
  'venue': 'MA Chidambaram Stadium',
  'team1': 'Chennai Super Kings',
  'team2': 'Royal Challengers Bangalore',
  'toss_winner': 'Chennai Super Kings',
  'toss_decision': 'bat',
  'winner': 'Chennai Super Kings',
  'result': 'runs',
  'result_margin': 21.0,
  'target_runs': 184.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'HDPK Dharmasena',
  'umpire2': 'AL Hill'},
 {'match_id': 501212,
  'season': 2011,
  'city': 'Hyderabad',
  'date': '2011-04-16',
  'match_type': 'League',
  'player_of_match': 'PC Valthaty',
  'venue': 'Rajiv Gandhi International Stadium',
  'team1': 'Sunrisers Hyderabad',
  'team2': 'Punjab Kings',
  'toss_winner': 'Punjab Kings',
  'toss_decision': 'field',
  'winner': 'Punjab Kings',
  'result': 'wickets',
  'result_margin': 8.0,
  'target_runs': 166.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'RE Koertzen',
  'umpire2': 'S Ravi'},
 {'match_id': 501213,
  'season': 2011,
  'city': 'Mumbai',
  'date': '2011-04-17',
  'match_type': 'League',
  'player_of_match': 'Yuvraj Singh',
  'venue': 'Dr DY Patil Sports Academy',
  'team1': 'Rising Pune Supergiant',
  'team2': 'Delhi Capitals',
  'toss_winner': 'Delhi Capitals',
  'toss_decision': 'field',
  'winner': 'Delhi Capitals',
  'result': 'wickets',
  'result_margin': 3.0,
  'target_runs': 188.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'Asad Rauf',
  'umpire2': 'AM Saheba'},
 {'match_id': 501214,
  'season': 2011,
  'city': 'Kolkata',
  'date': '2011-04-17',
  'match_type': 'League',
  'player_of_match': 'L Balaji',
  'venue': 'Eden Gardens',
  'team1': 'Kolkata Knight Riders',
  'team2': 'Rajasthan Royals',
  'toss_winner': 'Kolkata Knight Riders',
  'toss_decision': 'field',
  'winner': 'Kolkata Knight Riders',
  'result': 'wickets',
  'result_margin': 8.0,
  'target_runs': 82.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'Aleem Dar',
  'umpire2': 'RB Tiffin'},
 {'match_id': 501215,
  'season': 2011,
  'city': None,
  'date': '2011-04-18',
  'match_type': 'League',
  'player_of_match': 'BB McCullum',
  'venue': 'Nehru Stadium',
  'team1': 'Kochi Tuskers Kerala',
  'team2': 'Chennai Super Kings',
  'toss_winner': 'Kochi Tuskers Kerala',
  'toss_decision': 'field',
  'winner': 'Kochi Tuskers Kerala',
  'result': 'wickets',
  'result_margin': 7.0,
  'target_runs': 135.0,
  'target_overs': 17.0,
  'super_over': 'N',
  'method': 'D/L',
  'umpire1': 'K Hariharan',
  'umpire2': 'AL Hill'},
 {'match_id': 501216,
  'season': 2011,
  'city': 'Delhi',
  'date': '2011-04-19',
  'match_type': 'League',
  'player_of_match': 'S Sohal',
  'venue': 'Feroz Shah Kotla',
  'team1': 'Delhi Capitals',
  'team2': 'Sunrisers Hyderabad',
  'toss_winner': 'Sunrisers Hyderabad',
  'toss_decision': 'bat',
  'winner': 'Sunrisers Hyderabad',
  'result': 'runs',
  'result_margin': 16.0,
  'target_runs': 169.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'PR Reiffel',
  'umpire2': 'RJ Tucker'},
 {'match_id': 501218,
  'season': 2011,
  'city': 'Mumbai',
  'date': '2011-04-20',
  'match_type': 'League',
  'player_of_match': 'MM Patel',
  'venue': 'Wankhede Stadium',
  'team1': 'Mumbai Indians',
  'team2': 'Rising Pune Supergiant',
  'toss_winner': 'Rising Pune Supergiant',
  'toss_decision': 'bat',
  'winner': 'Mumbai Indians',
  'result': 'wickets',
  'result_margin': 7.0,
  'target_runs': 119.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'Asad Rauf',
  'umpire2': 'AM Saheba'},
 {'match_id': 501219,
  'season': 2011,
  'city': 'Kolkata',
  'date': '2011-04-20',
  'match_type': 'League',
  'player_of_match': 'DPMD Jayawardene',
  'venue': 'Eden Gardens',
  'team1': 'Kolkata Knight Riders',
  'team2': 'Kochi Tuskers Kerala',
  'toss_winner': 'Kolkata Knight Riders',
  'toss_decision': 'field',
  'winner': 'Kochi Tuskers Kerala',
  'result': 'runs',
  'result_margin': 6.0,
  'target_runs': 133.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'Aleem Dar',
  'umpire2': 'RB Tiffin'},
 {'match_id': 501220,
  'season': 2011,
  'city': 'Mohali',
  'date': '2011-04-21',
  'match_type': 'League',
  'player_of_match': 'SE Marsh',
  'venue': 'Punjab Cricket Association IS Bindra Stadium',
  'team1': 'Punjab Kings',
  'team2': 'Rajasthan Royals',
  'toss_winner': 'Rajasthan Royals',
  'toss_decision': 'field',
  'winner': 'Punjab Kings',
  'result': 'runs',
  'result_margin': 48.0,
  'target_runs': 196.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'S Asnani',
  'umpire2': 'PR Reiffel'},
 {'match_id': 501221,
  'season': 2011,
  'city': 'Mumbai',
  'date': '2011-04-22',
  'match_type': 'League',
  'player_of_match': 'Harbhajan Singh',
  'venue': 'Wankhede Stadium',
  'team1': 'Mumbai Indians',
  'team2': 'Chennai Super Kings',
  'toss_winner': 'Chennai Super Kings',
  'toss_decision': 'field',
  'winner': 'Mumbai Indians',
  'result': 'runs',
  'result_margin': 8.0,
  'target_runs': 165.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'Asad Rauf',
  'umpire2': 'AM Saheba'},
 {'match_id': 501222,
  'season': 2011,
  'city': 'Kolkata',
  'date': '2011-04-22',
  'match_type': 'League',
  'player_of_match': 'CH Gayle',
  'venue': 'Eden Gardens',
  'team1': 'Kolkata Knight Riders',
  'team2': 'Royal Challengers Bangalore',
  'toss_winner': 'Royal Challengers Bangalore',
  'toss_decision': 'field',
  'winner': 'Royal Challengers Bangalore',
  'result': 'wickets',
  'result_margin': 9.0,
  'target_runs': 172.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'SS Hazare',
  'umpire2': 'RB Tiffin'},
 {'match_id': 501223,
  'season': 2011,
  'city': 'Delhi',
  'date': '2011-04-23',
  'match_type': 'League',
  'player_of_match': 'DA Warner',
  'venue': 'Feroz Shah Kotla',
  'team1': 'Delhi Capitals',
  'team2': 'Punjab Kings',
  'toss_winner': 'Punjab Kings',
  'toss_decision': 'field',
  'winner': 'Delhi Capitals',
  'result': 'runs',
  'result_margin': 29.0,
  'target_runs': 232.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'S Asnani',
  'umpire2': 'RE Koertzen'},
 {'match_id': 501224,
  'season': 2011,
  'city': 'Hyderabad',
  'date': '2011-04-24',
  'match_type': 'League',
  'player_of_match': 'SL Malinga',
  'venue': 'Rajiv Gandhi International Stadium',
  'team1': 'Sunrisers Hyderabad',
  'team2': 'Mumbai Indians',
  'toss_winner': 'Sunrisers Hyderabad',
  'toss_decision': 'field',
  'winner': 'Mumbai Indians',
  'result': 'runs',
  'result_margin': 37.0,
  'target_runs': 173.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'HDPK Dharmasena',
  'umpire2': 'AL Hill'},
 {'match_id': 501225,
  'season': 2011,
  'city': 'Jaipur',
  'date': '2011-04-24',
  'match_type': 'League',
  'player_of_match': 'SK Warne',
  'venue': 'Sawai Mansingh Stadium',
  'team1': 'Rajasthan Royals',
  'team2': 'Kochi Tuskers Kerala',
  'toss_winner': 'Rajasthan Royals',
  'toss_decision': 'field',
  'winner': 'Rajasthan Royals',
  'result': 'wickets',
  'result_margin': 8.0,
  'target_runs': 110.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'BR Doctrove',
  'umpire2': 'SK Tarapore'},
 {'match_id': 501226,
  'season': 2011,
  'city': 'Chennai',
  'date': '2011-04-25',
  'match_type': 'League',
  'player_of_match': 'MEK Hussey',
  'venue': 'MA Chidambaram Stadium',
  'team1': 'Chennai Super Kings',
  'team2': 'Rising Pune Supergiant',
  'toss_winner': 'Rising Pune Supergiant',
  'toss_decision': 'field',
  'winner': 'Chennai Super Kings',
  'result': 'runs',
  'result_margin': 25.0,
  'target_runs': 143.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'Aleem Dar',
  'umpire2': 'RB Tiffin'},
 {'match_id': 501227,
  'season': 2011,
  'city': 'Delhi',
  'date': '2011-04-26',
  'match_type': 'League',
  'player_of_match': 'V Kohli',
  'venue': 'Feroz Shah Kotla',
  'team1': 'Delhi Capitals',
  'team2': 'Royal Challengers Bangalore',
  'toss_winner': 'Royal Challengers Bangalore',
  'toss_decision': 'field',
  'winner': 'Royal Challengers Bangalore',
  'result': 'wickets',
  'result_margin': 3.0,
  'target_runs': 161.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'S Asnani',
  'umpire2': 'RJ Tucker'},
 {'match_id': 501228,
  'season': 2011,
  'city': 'Mumbai',
  'date': '2011-04-27',
  'match_type': 'League',
  'player_of_match': 'DE Bollinger',
  'venue': 'Dr DY Patil Sports Academy',
  'team1': 'Rising Pune Supergiant',
  'team2': 'Chennai Super Kings',
  'toss_winner': 'Rising Pune Supergiant',
  'toss_decision': 'bat',
  'winner': 'Chennai Super Kings',
  'result': 'wickets',
  'result_margin': 8.0,
  'target_runs': 142.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'Asad Rauf',
  'umpire2': 'SL Shastri'},
 {'match_id': 501229,
  'season': 2011,
  'city': None,
  'date': '2011-04-27',
  'match_type': 'League',
  'player_of_match': 'I Sharma',
  'venue': 'Nehru Stadium',
  'team1': 'Kochi Tuskers Kerala',
  'team2': 'Sunrisers Hyderabad',
  'toss_winner': 'Kochi Tuskers Kerala',
  'toss_decision': 'field',
  'winner': 'Sunrisers Hyderabad',
  'result': 'runs',
  'result_margin': 55.0,
  'target_runs': 130.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'HDPK Dharmasena',
  'umpire2': 'AL Hill'},
 {'match_id': 501230,
  'season': 2011,
  'city': 'Delhi',
  'date': '2011-04-28',
  'match_type': 'League',
  'player_of_match': 'MK Tiwary',
  'venue': 'Feroz Shah Kotla',
  'team1': 'Delhi Capitals',
  'team2': 'Kolkata Knight Riders',
  'toss_winner': 'Delhi Capitals',
  'toss_decision': 'field',
  'winner': 'Kolkata Knight Riders',
  'result': 'runs',
  'result_margin': 17.0,
  'target_runs': 149.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'PR Reiffel',
  'umpire2': 'RJ Tucker'},
 {'match_id': 501231,
  'season': 2011,
  'city': 'Jaipur',
  'date': '2011-04-29',
  'match_type': 'League',
  'player_of_match': 'J Botha',
  'venue': 'Sawai Mansingh Stadium',
  'team1': 'Rajasthan Royals',
  'team2': 'Mumbai Indians',
  'toss_winner': 'Rajasthan Royals',
  'toss_decision': 'field',
  'winner': 'Rajasthan Royals',
  'result': 'wickets',
  'result_margin': 7.0,
  'target_runs': 95.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'Asad Rauf',
  'umpire2': 'SK Tarapore'},
 {'match_id': 501232,
  'season': 2011,
  'city': 'Bengaluru',
  'date': '2011-04-29',
  'match_type': 'League',
  'player_of_match': 'V Kohli',
  'venue': 'M Chinnaswamy Stadium',
  'team1': 'Royal Challengers Bangalore',
  'team2': 'Rising Pune Supergiant',
  'toss_winner': 'Rising Pune Supergiant',
  'toss_decision': 'field',
  'winner': 'Royal Challengers Bangalore',
  'result': 'runs',
  'result_margin': 26.0,
  'target_runs': 182.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'Aleem Dar',
  'umpire2': 'SS Hazare'},
 {'match_id': 501233,
  'season': 2011,
  'city': None,
  'date': '2011-04-30',
  'match_type': 'League',
  'player_of_match': 'V Sehwag',
  'venue': 'Nehru Stadium',
  'team1': 'Kochi Tuskers Kerala',
  'team2': 'Delhi Capitals',
  'toss_winner': 'Delhi Capitals',
  'toss_decision': 'bat',
  'winner': 'Delhi Capitals',
  'result': 'runs',
  'result_margin': 38.0,
  'target_runs': 158.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'HDPK Dharmasena',
  'umpire2': 'AL Hill'},
 {'match_id': 501234,
  'season': 2011,
  'city': 'Kolkata',
  'date': '2011-04-30',
  'match_type': 'League',
  'player_of_match': 'Iqbal Abdulla',
  'venue': 'Eden Gardens',
  'team1': 'Kolkata Knight Riders',
  'team2': 'Punjab Kings',
  'toss_winner': 'Kolkata Knight Riders',
  'toss_decision': 'field',
  'winner': 'Kolkata Knight Riders',
  'result': 'wickets',
  'result_margin': 8.0,
  'target_runs': 120.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'AM Saheba',
  'umpire2': 'SL Shastri'},
 {'match_id': 501235,
  'season': 2011,
  'city': 'Jaipur',
  'date': '2011-05-01',
  'match_type': 'League',
  'player_of_match': 'LRPL Taylor',
  'venue': 'Sawai Mansingh Stadium',
  'team1': 'Rajasthan Royals',
  'team2': 'Rising Pune Supergiant',
  'toss_winner': 'Rajasthan Royals',
  'toss_decision': 'field',
  'winner': 'Rajasthan Royals',
  'result': 'wickets',
  'result_margin': 6.0,
  'target_runs': 144.0,
  'target_overs': 20.0,
  'super_over': 'N',
  'method': None,
  'umpire1': 'SK Tarapore',
  'umpire2': 'SJA Taufel'},
 {'match_id': 501236,
  'season': 2011,
  'city': 'Chennai',
  'date': '2011-05-01',
  'match_type': 'League',

## B)Teams API

### 1) Team Performance

a) overall team performance

- by taking input as team name it will return total matches played by the team, season wins losses, winning percentages, total runsmade by team, players name, top 5 scores ie runs scored respective seasons, average score (median)

In [38]:
ipl2.columns

Index(['match_id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2'],
      dtype='object')

In [39]:
data=ipl1.merge(ipl2[['match_id','season']],on = 'match_id')

In [40]:
def team_performance(team):
    if team in team_name()['Team_Name']:
        # To find sum of runs in respective seasons by the team
        team_runs_season = data.groupby(['batting_team', 'season'])['total_runs'].sum()
        team_runs_season = team_runs_season[team].to_dict() if team in team_runs_season.index.get_level_values(0) else {}

        # List of batters for the team across all seasons
        batters = list(data[data['batting_team'] == team]['batter'].unique())

        # List of bowlers for the team across all seasons
        bowlers = list(data[data['bowling_team'] == team]['bowler'].unique())

        # Total matches played by the team
        total_matches = ipl2[(ipl2['team1'] == team) | (ipl2['team2'] == team)]['match_id'].nunique()

        # Number of matches played as qualifiers
        qualifier = ipl2[ipl2['match_type'] != 'League']
        qualifier_team = qualifier[(qualifier['team1'] == team) | (qualifier['team2'] == team)]
        if not qualifier_team.empty:
            qualifier_team_season = list(qualifier_team['season'].unique())
        else:
            qualifier_team_season = f"{team} never qualified"

        # Number of matches played in finals
        finals = ipl2[ipl2['match_type'] == 'Final']
        final_team = finals[(finals['team1'] == team) | (finals['team2'] == team)]
        finalized = final_team.shape[0]

        # Number of finals won
        if not final_team.empty:
            final_win_count = final_team[final_team['winner'] == team].shape[0]
            if final_win_count == 0:
                winned_matches = f"{team} never won the finals"
            else:
                winned_matches = final_win_count
        else:
            winned_matches = f"{team} never went to finals"

        # Number of finals lost
        if isinstance(winned_matches, int):
            lossed_matches = finalized - winned_matches
        else:
            lossed_matches = f"{team} never reached the finals"

        # Winning percentage across all matches
        matches_played = ipl2[(ipl2['team1'] == team) | (ipl2['team2'] == team)]
        winned_matches_overall = matches_played[matches_played['winner'] == team]
        if matches_played.shape[0] > 0:
            winning_percentage = (winned_matches_overall.shape[0] / matches_played.shape[0]) * 100
        else:
            winning_percentage = 0

        # Prepare the final response dictionary
        final_response = {
            'seasonwise_runs': team_runs_season,
            'batters': batters,
            'bowlers': bowlers,
            'total_matches': total_matches,
            'qualified_matches_season': qualifier_team_season,
            'finals_played': finalized,
            'wins': winned_matches,
            'losses': lossed_matches,
            'winning_percentage_overall': f"{round(winning_percentage, 2)}%"
        }

        return final_response
    else:
        return {"error": f"Team '{team}' not found in the dataset"}

In [41]:
team_performance('Mumbai Indians')

{'seasonwise_runs': {2008: 2080,
  2009: 1897,
  2010: 2738,
  2011: 2288,
  2012: 2462,
  2013: 2975,
  2014: 2353,
  2015: 2734,
  2016: 2194,
  2017: 2800,
  2018: 2380,
  2019: 2670,
  2020: 2758,
  2021: 2117,
  2022: 2217,
  2023: 2945,
  2024: 2568},
 'batters': ['L Ronchi',
  'ST Jayasuriya',
  'DJ Thornely',
  'RV Uthappa',
  'PR Shah',
  'AM Nayar',
  'SM Pollock',
  'Harbhajan Singh',
  'DJ Bravo',
  'MA Khote',
  'A Nehra',
  'SS Tiwary',
  'DS Kulkarni',
  'AM Rahane',
  'MK Pandey',
  'YV Takawale',
  'RR Raje',
  'SR Tendulkar',
  'DR Smith',
  'SD Chitnis',
  'CRD Fernando',
  'VS Yeligati',
  'S Dhawan',
  'JP Duminy',
  'Z Khan',
  'GR Napier',
  'C Nanda',
  'SL Malinga',
  'Mohammad Ashraful',
  'AP Tare',
  'AT Rayudu',
  'R Sathish',
  'R McLaren',
  'KA Pollard',
  'AN Ahmed',
  'C Madan',
  'STR Binny',
  'DJ Jacobs',
  'RG Sharma',
  'JEC Franklin',
  'A Symonds',
  'AG Murtaza',
  'AC Blizzard',
  'TL Suman',
  'MM Patel',
  'RE Levi',
  'KD Karthik',
  'SA Yadav',
  'PP Ojha',
  'CJ McKay',
  'RP Singh',
  'NLTC Perera',
  'RJ Peterson',
  'HH Gibbs',
  'RT Ponting',
  'R Dhawan',
  'MG Johnson',
  'GJ Maxwell',
  'NM Coulter-Nile',
  'MEK Hussey',
  'CJ Anderson',
  'CM Gautam',
  'JJ Bumrah',
  'BR Dunk',
  'LMP Simmons',
  'S Gopal',
  'M de Lange',
  'P Kumar',
  'AJ Finch',
  'J Suchith',
  'PA Patel',
  'UBT Chand',
  'R Vinay Kumar',
  'HH Pandya',
  'MJ McClenaghan',
  'JC Buttler',
  'KH Pandya',
  'TG Southee',
  'MJ Guptill',
  'N Rana',
  'KV Sharma',
  'E Lewis',
  'Ishan Kishan',
  'BCJ Cutting',
  'PJ Sangwan',
  'M Markande',
  'A Dananjaya',
  'Mustafizur Rahman',
  'Q de Kock',
  'Yuvraj Singh',
  'Rasikh Salam',
  'RD Chahar',
  'SD Lad',
  'AS Joseph',
  'BB Sran',
  'JL Pattinson',
  'TA Boult',
  'CA Lynn',
  'M Jansen',
  'J Yadav',
  'JDS Neesham',
  'PP Chawla',
  'AF Milne',
  'Anmolpreet Singh',
  'Tilak Varma',
  'TH David',
  'DR Sams',
  'M Ashwin',
  'D Brevis',
  'Ramandeep Singh',
  'JD Unadkat',
  'TS Mills',
  'FA Allen',
  'HR Shokeen',
  'K Kartikeya',
  'RP Meredith',
  'T Stubbs',
  'R Sanjay Yadav',
  'C Green',
  'N Wadhera',
  'Arshad Khan',
  'JC Archer',
  'Arjun Tendulkar',
  'JP Behrendorff',
  'Vishnu Vinod',
  'CJ Jordan',
  'Naman Dhir',
  'G Coetzee',
  'SZ Mulani',
  'R Shepherd',
  'Akash Madhwal',
  'Mohammad Nabi',
  'L Wood',
  'A Kamboj'],
 'bowlers': ['A Nehra',
  'SM Pollock',
  'DS Kulkarni',
  'ST Jayasuriya',
  'Harbhajan Singh',
  'AM Nayar',
  'DJ Bravo',
  'VS Yeligati',
  'MA Khote',
  'SD Chitnis',
  'CRD Fernando',
  'DJ Thornely',
  'RR Raje',
  'DR Smith',
  'A Nel',
  'SL Malinga',
  'Z Khan',
  'SR Tendulkar',
  'JP Duminy',
  'GR Napier',
  'C Nanda',
  'AM Rahane',
  'RA Shaikh',
  'R McLaren',
  'AG Murtaza',
  'R Sathish',
  'KA Pollard',
  'AN Ahmed',
  'STR Binny',
  'MM Patel',
  'JEC Franklin',
  'RG Sharma',
  'TL Suman',
  'A Symonds',
  'RW Price',
  'PP Ojha',
  'RP Singh',
  'CJ McKay',
  'NLTC Perera',
  'RJ Peterson',
  'R Shukla',
  'MG Johnson',
  'JJ Bumrah',
  'JDP Oram',
  'R Dhawan',
  'YS Chahal',
  'P Suyal',
  'GJ Maxwell',
  'NM Coulter-Nile',
  'CJ Anderson',
  'P Kumar',
  'LMP Simmons',
  'K Santokie',
  'S Gopal',
  'M de Lange',
  'R Vinay Kumar',
  'J Suchith',
  'MJ McClenaghan',
  'HH Pandya',
  'TG Southee',
  'KH Pandya',
  'N Rana',
  'KV Sharma',
  'Mustafizur Rahman',
  'M Markande',
  'PJ Sangwan',
  'BCJ Cutting',
  'A Dananjaya',
  'Rasikh Salam',
  'JP Behrendorff',
  'RD Chahar',
  'AS Joseph',
  'J Yadav',
  'AS Roy',
  'BB Sran',
  'TA Boult',
  'JL Pattinson',
  'M Jansen',
  'AF Milne',
  'JDS Neesham',
  'PP Chawla',
  'DR Sams',
  'Basil Thampi',
  'M Ashwin',
  'TS Mills',
  'Tilak Varma',
  'JD Unadkat',
  'D Brevis',
  'FA Allen',
  'RP Meredith',
  'HR Shokeen',
  'K Kartikeya',
  'Ramandeep Singh',
  'R Sanjay Yadav',
  'Arshad Khan',
  'JC Archer',
  'C Green',
  'Arjun Tendulkar',
  'D Jansen',
  'Akash Madhwal',
  'R Goyal',
  'T Stubbs',
  'CJ Jordan',
  'L Wood',
  'SZ Mulani',
  'Naman Dhir',
  'G Coetzee',
  'KT Maphaka',
  'R Shepherd',
  'Mohammad Nabi',
  'N Thushara',
  'A Kamboj',
  'N Wadhera'],
 'total_matches': 261,
 'qualified_matches_season': [2010,
  2011,
  2012,
  2013,
  2014,
  2015,
  2017,
  2019,
  2020,
  2023],
 'finals_played': 6,
 'wins': 5,
 'losses': 1,
 'winning_percentage_overall': '55.17%'}

## 2) Head-to-Head performance:

### i. SeasonWise

In [44]:
def HTH_season(team1,team2,season):

    # fetched both teams from team1 and team2 column according to the season
    possiblity1=ipl2[(ipl2['team1']==team1)&(ipl2['team2']==team2)&(ipl2['season']==season)]
    possiblity2=ipl2[(ipl2['team1']==team2)&(ipl2['team2']==team1)&(ipl2['season']==season)]

    # checked whether details are available for the details or not and showed result
    if not possiblity1.empty and not possiblity2.empty:
        matches=pd.concat([possiblity1,possiblity2])
        records=matches[['match_id','season','date','match_type','city','venue','toss_winner','toss_decision','winner','target_runs','player_of_match']]
        response=json.loads(records.to_json(index=False,orient='records'))
        return response
    else:
        return {'error':'no records founds regarding to data'}

In [45]:
HTH_season('Mumbai Indians','Chennai Super Kings',2009)

{'error': 'no records founds regarding to data'}

In [46]:
possiblity1=ipl2[(ipl2['team1']=='Mumbai Indians')&(ipl2['team2']=='Chennai Super Kings')&(ipl2['season']==2009)]
possiblity2=ipl2[(ipl2['team1']=='Chennai Super Kings')&(ipl2['team2']=='Mumbai Indians')&(ipl2['season']==2009)]

# checked whether details are available for the details or not and showed result
if not possiblity1.empty and not possiblity2.empty:
    matches=pd.concat([possiblity1,possiblity2])
    records=matches[['match_id','season','date','match_type','city','venue','toss_winner','toss_decision','winner','target_runs','player_of_match']]

In [47]:
ipl2[ipl2['season']==2009]

,match_id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
58,392181,2009,Cape Town,2009-04-18,League,SR Tendulkar,Newlands,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,field,Mumbai Indians,runs,19.0,166.0,20.0,N,NaN,BR Doctrove,K Hariharan
59,392182,2009,Cape Town,2009-04-18,League,R Dravid,Newlands,Royal Challengers Bangalore,Rajasthan Royals,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,runs,75.0,134.0,20.0,N,NaN,BR Doctrove,RB Tiffin
60,392183,2009,Cape Town,2009-04-19,League,DL Vettori,Newlands,Delhi Capitals,Punjab Kings,Delhi Capitals,field,Delhi Capitals,wickets,10.0,54.0,6.0,N,D/L,MR Benson,SD Ranade
61,392184,2009,Cape Town,2009-04-19,League,RP Singh,Newlands,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,bat,Sunrisers Hyderabad,wickets,8.0,102.0,20.0,N,NaN,MR Benson,BR Doctrove
62,392185,2009,Port Elizabeth,2009-04-20,League,M Muralitharan,St George's Park,Royal Challengers Bangalore,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,92.0,180.0,20.0,N,NaN,BG Jerling,SJA Taufel
63,392186,2009,Durban,2009-04-21,League,CH Gayle,Kingsmead,Punjab Kings,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,runs,11.0,69.0,9.2,N,D/L,DJ Harper,SD Ranade
64,392188,2009,Cape Town,2009-04-22,League,AC Gilchrist,Newlands,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,runs,24.0,185.0,20.0,N,NaN,M Erasmus,AM Saheba
65,392189,2009,Durban,2009-04-23,League,AB de Villiers,Kingsmead,Chennai Super Kings,Delhi Capitals,Delhi Capitals,bat,Delhi Capitals,runs,9.0,190.0,20.0,N,NaN,BR Doctrove,SJA Taufel
66,392190,2009,Cape Town,2009-04-23,League,YK Pathan,Newlands,Kolkata Knight Riders,Rajasthan Royals,Kolkata Knight Riders,field,Rajasthan Royals,tie,NaN,151.0,20.0,Y,NaN,MR Benson,M Erasmus
67,392191,2009,Durban,2009-04-24,League,RS Bopara,Kingsmead,Royal Challengers Bangalore,Punjab Kings,Royal Challengers Bangalore,bat,Punjab Kings,wickets,7.0,169.0,20.0,N,NaN,BR Doctrove,TH Wijewardene
68,392192,2009,Durban,2009-04-25,League,PP Ojha,Kingsmead,Sunrisers Hyderabad,Mumbai Indians,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,runs,12.0,169.0,20.0,N,NaN,HDPK Dharmasena,SJA Taufel
69,392194,2009,Port Elizabeth,2009-04-26,League,TM Dilshan,St George's Park,Royal Challengers Bangalore,Delhi Capitals,Royal Challengers Bangalore,bat,Delhi Capitals,wickets,6.0,150.0,20.0,N,NaN,S Asnani,BG Jerling
70,392195,2009,Cape Town,2009-04-26,League,KC Sangakkara,Newlands,Punjab Kings,Rajasthan Royals,Punjab Kings,bat,Punjab Kings,runs,27.0,140.0,20.0,N,NaN,M Erasmus,K Hariharan
71,392196,2009,Durban,2009-04-27,League,HH Gibbs,Kingsmead,Chennai Super Kings,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,166.0,20.0,N,NaN,IL Howell,TH Wijewardene
72,392197,2009,Port Elizabeth,2009-04-27,League,SR Tendulkar,St George's Park,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,bat,Mumbai Indians,runs,92.0,188.0,20.0,N,NaN,BG Jerling,RB Tiffin
73,392198,2009,Centurion,2009-04-28,League,YK Pathan,SuperSport Park,Delhi Capitals,Rajasthan Royals,Delhi Capitals,bat,Rajasthan Royals,wickets,5.0,144.0,20.0,N,NaN,GAV Baxter,RE Koertzen
74,392199,2009,Durban,2009-04-29,League,MV Boucher,Kingsmead,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,bat,Royal Challengers Bangalore,wickets,5.0,140.0,20.0,N,NaN,MR Benson,TH Wijewardene
75,392200,2009,Durban,2009-04-29,League,KC Sangakkara,Kingsmead,Punjab Kings,Mumbai Indians,Punjab Kings,bat,Punjab Kings,runs,3.0,120.0,20.0,N,NaN,MR Benson,SL Shastri
76,392201,2009,Centurion,2009-04-30,League,DP Nannes,SuperSport Park,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,Delhi Capitals,wickets,6.0,149.0,20.0,N,NaN,GAV Baxter,AM Saheba
77,392202,2009,Centurion,2009-04-30,League,SK Raina,SuperSport Park,Chennai Super Kings,Rajasthan Royals,Rajasthan Royals,field,Chennai Super Kings,runs,38.0,165.0,20.0,N,NaN,GAV Baxter,RE Koertzen
78,392203,2009,East London,2009-05-01,League,JP Duminy,Buffalo Park,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,bat,Mumbai Indians,runs,9.0,149.0,20.0,N,NaN,M Erasmus,SK Tarapore
79,392204,2009,Durban,2009-05-01,League,Yuvraj Singh,Kingsmead,Royal Challengers Bangalore,Punjab Kings,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,runs,8.0,146.0,20.0,N,NaN,HDPK Dharmasena,S Ravi
80,392205,2009,Port Elizabeth,2009-05-02,League,YK Pathan,St George's Park,Sunrisers Hyderabad,Rajasthan Royals,Sunrisers Hyderabad,bat,Rajasthan Royals,wickets,3.0,142.0,20.0,N,NaN,S Asnani,BG Jerling
81,392206,2009,Johannesburg,2009-05-02,League,SB Jakati,New Wanderers Stadium,Chennai Super Kings,Delhi Capitals,Delhi Capitals,field,Chennai Super Kings,runs,18.0,164.0,20.0,N,NaN,DJ Harper,RE Koertzen
82,392207,2009,Port Elizabeth,2009-05-03,League,DPMD Jayawardene,St George's Park,Punjab Kings,Kolkata Knight Riders,Kolkata Knight Riders,bat,Punjab Kings,wickets,6.0,154.0,20.0,N,NaN,S Asnani,MR Benson
83,392208,2009,Johannesburg,2009-05-03,League,JH Kallis,New Wanderers Stadium,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,9.0,150.0,20.0,N,NaN,RE Koertzen,TH Wijewardene
84,392209,2009,East London,2009-05-04,League,MS Dhoni,Buffalo Park,Chennai Super Kings,Sunrisers Hyderabad,Chennai Super Kings,bat,Chennai Super Kings,runs,78.0,179.0,20.0,N,NaN,BR Doctrove,M Erasmus
85,392210,2009,Durban,2009-05-05,League,GC Smith,Kingsmead,Punjab Kings,Rajasthan Royals,Punjab Kings,field,Rajasthan Royals,runs,78.0,212.0,20.0,N,NaN,SS Hazare,IL Howell
86,392211,2009,Durban,2009-05-05,League,G Gambhir,Kingsmead,Delhi Capitals,Kolkata Knight Riders,Kolkata Knight Riders,bat,Delhi Capitals,wickets,9.0,155.0,20.0,N,NaN,GAV Baxter,IL Howell
87,392212,2009,Centurion,2009-05-06,League,RG Sharma,SuperSport Park,Sunrisers Hyderabad,Mumbai Indians,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,runs,19.0,146.0,20.0,N,NaN,MR Benson,HDPK Dharmasena
88,392213,2009,Centurion,2009-05-07,League,A Singh,SuperSport Park,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,7.0,106.0,20.0,N,NaN,K Hariharan,DJ Harper
89,392214,2009,Centurion,2009-05-07,League,ML Hayden,SuperSport Park,Chennai Super Kings,Punjab Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,12.0,187.0,18.0,N,D/L,DJ Harper,TH Wijewardene
90,392215,2009,East London,2009-05-08,League,A Nehra,Buffalo Park,Delhi Capitals,Mumbai Indians,Mumbai Indians,bat,Delhi Capitals,wickets,7.0,117.0,20.0,N,NaN,M Erasmus,SK Tarapore
91,392216,2009,Kimberley,2009-05-09,League,DPMD Jayawardene,De Beers Diamond Oval,Sunrisers Hyderabad,Punjab Kings,Punjab Kings,field,Punjab Kings,wickets,3.0,169.0,20.0,N,NaN,GAV Baxter,AM Saheba
92,392217,2009,Kimberley,2009-05-09,League,S Badrinath,De Beers Diamond Oval,Chennai Super Kings,Rajasthan Royals,Rajasthan Royals,bat,Chennai Super Kings,wickets,7.0,141.0,20.0,N,NaN,GAV Baxter,HDPK Dharmasena
93,392218,2009,Port Elizabeth,2009-05-10,League,JP Duminy,St George's Park,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,bat,Mumbai Indians,runs,16.0,158.0,20.0,N,NaN,BR Doctrove,BG Jerling
94,392219,2009,Johannesburg,2009-05-10,League,A Mishra,New Wanderers Stadium,Delhi Capitals,Kolkata Knight Riders,Delhi Capitals,field,Delhi Capitals,wickets,7.0,124.0,20.0,N,NaN,SL Shastri,RB Tiffin
95,392220,2009,Kimberley,2009-05-11,League,DR Smith,De Beers Diamond Oval,Sunrisers Hyderabad,Rajasthan Royals,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,runs,53.0,167.0,20.0,N,NaN,GAV Baxter,HDPK Dharmasena
96,392221,2009,Centurion,2009-05-12,League,LRPL Taylor,SuperSport Park,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,6.0,174.0,20.0,N,NaN,M Erasmus,SS Hazare
97,392222,2009,Centurion,2009-05-12,League,Harbhajan Singh,SuperSport Park,Punjab Kings,Mumbai Indians,Punjab Kings,bat,Mumbai Indians,wickets,8.0,120.0,20.0,N,NaN,SS Hazare,RE Koertzen
98,392223,2009,Durban,2009-05-13,League,R Bhatia,Kingsmead,Sunrisers Hyderabad,Delhi Capitals,Sunrisers Hyderabad,field,Delhi Capitals,runs,12.0,174.0,20.0,N,NaN,DJ Harper,SL Shastri
99,392224,2009,Durban,2009-05-14,League,LRPL Taylor,Kingsmead,Royal Challengers Bangalore,Chennai Super Kings,Chennai Super Kings,bat,Royal Challengers Bangalore,wickets,2.0,130.0,20.0,N,NaN,BR Doctrove,DJ Harper
100,392225,2009,Durban,2009-05-14,League,SK Warne,Kingsmead,Mumbai Indians,Rajasthan Royals,Rajasthan Royals,bat,Rajasthan Royals,runs,2.0,146.0,20.0,N,NaN,BR Doctrove,DJ Harper
101,392226,2009,Bloemfontein,2009-05-15,League,B Lee,OUTsurance Oval,Delhi Capitals,Punjab Kings,Punjab Kings,field,Punjab Kings,wickets,6.0,121.0,20.0,N,NaN,HDPK Dharmasena,IL Howell
102,392227,2009,Port Elizabeth,2009-05-16,League,ML Hayden,St George's Park,Chennai Super Kings,Mumbai Indians,Mumbai Indians,bat,Chennai Super Kings,wickets,7.0,148.0,20.0,N,NaN,SK Tarapore,SJA Taufel
103,392228,2009,Johannesburg,2009-05-16,League,RG Sharma,New Wanderers Stadium,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,161.0,20.0,N,NaN,RE Koertzen,S Ravi
104,392229,2009,Johannesburg,2009-05-17,League,Yuvraj Singh,New Wanderers Stadium,Sunrisers Hyderabad,Punjab Kings,Sunrisers Hyderabad,field,Punjab Kings,runs,1.0,135.0,20.0,N,NaN,S Ravi,RB Tiffin
105,392230,2009,Bloemfontein,2009-05-17,League,AB de Villiers,OUTsurance Oval,Delhi Capitals,Rajasthan Royals,Delhi Capitals,bat,Delhi Capitals,runs,14.0,151.0,20.0,N,NaN,SS Hazare,IL Howell
106,392231,2009,Centurion,2009-05-18,League,BJ Hodge,SuperSport Park,Chennai Super Kings,Kolkata Knight Riders,Chennai Super Kings,bat,Kolkata Knight Riders,wickets,7.0,189.0,20.0,N,NaN,SJA Taufel,RB Tiffin
107,392232,2009,Johannesburg,2009-05-19,League,JH Kallis,New Wanderers Stadium,Royal Challengers Bangalore,Delhi Capitals,Delhi Capitals,bat,Royal Challengers Bangalore,wickets,7.0,135.0,20.0,N,NaN,IL Howell,RB Tiffin
108,392233,2009,Durban,2009-05-20,League,LR Shukla,Kingsmead,Kolkata Knight Riders,Rajasthan Royals,Kolkata Knight Riders,field,Kolkata Knight Riders,wickets,4.0,102.0,20.0,N,NaN,BG Jerling,SJA Taufel
109,392234,2009,Durban,2009-05-20,League,M Muralitharan,Kingsmead,Chennai Super Kings,Punjab Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,24.0,117.0,20.0,N,NaN,BG Jerling,SJA Taufel
110,392235,2009,Centurion,2009-05-21,League,V Sehwag,SuperSport Park,Delhi Capitals,Mumbai Indians,Delhi Capitals,field,Delhi Capitals,wickets,4.0,166.0,20.0,N,NaN,IL Howell,S Ravi
111,392236,2009,Centurion,2009-05-21,League,MK Pandey,SuperSport Park,Royal Challengers Bangalore,Sunrisers Hyderabad,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,runs,12.0,171.0,20.0,N,NaN,IL Howell,S Ravi
112,392237,2009,Centurion,2009-05-22,Semi Final,AC Gilchrist,SuperSport Park,Delhi Capitals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,154.0,20.0,N,NaN,BR Doctrove,DJ Harper
113,392238,2009,Johannesburg,2009-05-23,Semi Final,MK Pandey,New Wanderers Stadium,Royal Challengers Bangalore,Chennai Super Kings,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,6.0,147.0,20.0,N,NaN,RE Koertzen,SJA Taufel
114,392239,2009,Johannesburg,2009-05-24,Final,A Kumble,New Wanderers Stadium,Royal Challengers Bangalore,Sunrisers Hyderabad,Royal Challengers Bangalore,field,Sunrisers Hyderabad,runs,6.0,144.0,20.0,N,NaN,RE Koertzen,SJA Taufel

### ii. for all Seasons

In [49]:
def HTH_Overall(team1,team2):

    # extracting data with respect to teams
    matches=ipl2[((ipl2['team1']==team1)&(ipl2['team2']==team2))|
    ((ipl2['team2']==team1)&(ipl2['team1']==team2))]

    #checking emptiness
    if not matches.empty:

        # fetching the columns want to return
        records=matches[['match_id','season','date','match_type','city','venue','toss_winner','toss_decision','winner','target_runs','player_of_match']]
    
        # Number of matches they played against
        total_matches=records.shape[0]
    
        # Number of wins of team1
        team1_win=records[records['winner']==team1].shape[0]
    
        # Number of wins of team2
        team2_win=records[records['winner']==team2].shape[0]
    
        # Winning percentage of both teams
        winning_rate_team1=(team1_win/total_matches)*100
        winning_rate_team2=(team2_win/total_matches)*100
    
        # converted dataframe to json and to add further details converted to list 
        response=list(json.loads(records.to_json(orient='records')))
        result=response+([{'total_matches':total_matches},
                           {'wins_of_team1':team1_win},
                           {'wins_of_team2':team2_win},
                           {'winning_rate_team1':round(winning_rate_team1,2)},
                          {'winning_rate_team2':round(winning_rate_team2,2)}])
        return result
    else:
        return {'error':'data not available'}

In [50]:
HTH_Overall('Rajasthan Royals','Mumbai Indians')

[{'match_id': 336008,
  'season': 2008,
  'date': '2008-05-07',
  'match_type': 'League',
  'city': 'Mumbai',
  'venue': 'Dr DY Patil Sports Academy',
  'toss_winner': 'Mumbai Indians',
  'toss_decision': 'field',
  'winner': 'Mumbai Indians',
  'target_runs': 104.0,
  'player_of_match': 'A Nehra'},
 {'match_id': 336036,
  'season': 2008,
  'date': '2008-05-26',
  'match_type': 'League',
  'city': 'Jaipur',
  'venue': 'Sawai Mansingh Stadium',
  'toss_winner': 'Rajasthan Royals',
  'toss_decision': 'field',
  'winner': 'Rajasthan Royals',
  'target_runs': 146.0,
  'player_of_match': 'Sohail Tanvir'},
 {'match_id': 392225,
  'season': 2009,
  'date': '2009-05-14',
  'match_type': 'League',
  'city': 'Durban',
  'venue': 'Kingsmead',
  'toss_winner': 'Rajasthan Royals',
  'toss_decision': 'bat',
  'winner': 'Rajasthan Royals',
  'target_runs': 146.0,
  'player_of_match': 'SK Warne'},
 {'match_id': 419107,
  'season': 2010,
  'date': '2010-03-13',
  'match_type': 'League',
  'city': 'Mumbai',
  'venue': 'Brabourne Stadium',
  'toss_winner': 'Mumbai Indians',
  'toss_decision': 'bat',
  'winner': 'Mumbai Indians',
  'target_runs': 213.0,
  'player_of_match': 'YK Pathan'},
 {'match_id': 419150,
  'season': 2010,
  'date': '2010-04-11',
  'match_type': 'League',
  'city': 'Jaipur',
  'venue': 'Sawai Mansingh Stadium',
  'toss_winner': 'Rajasthan Royals',
  'toss_decision': 'field',
  'winner': 'Mumbai Indians',
  'target_runs': 175.0,
  'player_of_match': 'SR Tendulkar'},
 {'match_id': 501231,
  'season': 2011,
  'date': '2011-04-29',
  'match_type': 'League',
  'city': 'Jaipur',
  'venue': 'Sawai Mansingh Stadium',
  'toss_winner': 'Rajasthan Royals',
  'toss_decision': 'field',
  'winner': 'Rajasthan Royals',
  'target_runs': 95.0,
  'player_of_match': 'J Botha'},
 {'match_id': 501263,
  'season': 2011,
  'date': '2011-05-20',
  'match_type': 'League',
  'city': 'Mumbai',
  'venue': 'Wankhede Stadium',
  'toss_winner': 'Mumbai Indians',
  'toss_decision': 'bat',
  'winner': 'Rajasthan Royals',
  'target_runs': 134.0,
  'player_of_match': 'SR Watson'},
 {'match_id': 548317,
  'season': 2012,
  'date': '2012-04-11',
  'match_type': 'League',
  'city': 'Mumbai',
  'venue': 'Wankhede Stadium',
  'toss_winner': 'Rajasthan Royals',
  'toss_decision': 'field',
  'winner': 'Mumbai Indians',
  'target_runs': 198.0,
  'player_of_match': 'KA Pollard'},
 {'match_id': 548377,
  'season': 2012,
  'date': '2012-05-20',
  'match_type': 'League',
  'city': 'Jaipur',
  'venue': 'Sawai Mansingh Stadium',
  'toss_winner': 'Rajasthan Royals',
  'toss_decision': 'bat',
  'winner': 'Mumbai Indians',
  'target_runs': 163.0,
  'player_of_match': 'DR Smith'},
 {'match_id': 598019,
  'season': 2013,
  'date': '2013-04-17',
  'match_type': 'League',
  'city': 'Jaipur',
  'venue': 'Sawai Mansingh Stadium',
  'toss_winner': 'Rajasthan Royals',
  'toss_decision': 'bat',
  'winner': 'Rajasthan Royals',
  'target_runs': 180.0,
  'player_of_match': 'AM Rahane'},
 {'match_id': 598063,
  'season': 2013,
  'date': '2013-05-15',
  'match_type': 'League',
  'city': 'Mumbai',
  'venue': 'Wankhede Stadium',
  'toss_winner': 'Rajasthan Royals',
  'toss_decision': 'field',
  'winner': 'Mumbai Indians',
  'target_runs': 167.0,
  'player_of_match': 'AP Tare'},
 {'match_id': 598072,
  'season': 2013,
  'date': '2013-05-24',
  'match_type': 'Qualifier 2',
  'city': 'Kolkata',
  'venue': 'Eden Gardens',
  'toss_winner': 'Rajasthan Royals',
  'toss_decision': 'bat',
  'winner': 'Mumbai Indians',
  'target_runs': 166.0,
  'player_of_match': 'Harbhajan Singh'},
 {'match_id': 734017,
  'season': 2014,
  'date': '2014-05-19',
  'match_type': 'League',
  'city': 'Ahmedabad',
  'venue': 'Sardar Patel Stadium, Motera',
  'toss_winner': 'Mumbai Indians',
  'toss_decision': 'bat',
  'winner': 'Mumbai Indians',
  'target_runs': 179.0,
  'player_of_match': 'MEK Hussey'},
 {'match_id': 734041,
  'season': 2014,
  'date': '2014-05-25',
  'match_type': 'League',
  'city': 'Mumbai',
  'venue': 'Wankhede Stadium',
  'toss_winner': 'Mumbai Indians',
  'toss_decision': 'field',
  'winner': 'Mumbai Indians',
  'target_runs': 190.0,
  'player_of_match': 'CJ Anderson'},
 {'match_id': 829721,
  'season': 2015,
  'date': '2015-04-14',
  'match_type': 'League',
  'city': 'Ahmedabad',
  'venue': 'Sardar Patel Stadium, Motera',
  'toss_winner': 'Mumbai Indians',
  'toss_decision': 'bat',
  'winner': 'Rajasthan Royals',
  'target_runs': 165.0,
  'player_of_match': 'SPD Smith'},
 {'match_id': 829769,
  'season': 2015,
  'date': '2015-05-01',
  'match_type': 'League',
  'city': 'Mumbai',
  'venue': 'Wankhede Stadium',
  'toss_winner': 'Rajasthan Royals',
  'toss_decision': 'field',
  'winner': 'Mumbai Indians',
  'target_runs': 188.0,
  'player_of_match': 'AT Rayudu'},
 {'match_id': 1136581,
  'season': 2018,
  'date': '2018-04-22',
  'match_type': 'League',
  'city': 'Jaipur',
  'venue': 'Sawai Mansingh Stadium',
  'toss_winner': 'Mumbai Indians',
  'toss_decision': 'bat',
  'winner': 'Rajasthan Royals',
  'target_runs': 168.0,
  'player_of_match': 'JC Archer'},
 {'match_id': 1136607,
  'season': 2018,
  'date': '2018-05-13',
  'match_type': 'League',
  'city': 'Mumbai',
  'venue': 'Wankhede Stadium',
  'toss_winner': 'Rajasthan Royals',
  'toss_decision': 'field',
  'winner': 'Rajasthan Royals',
  'target_runs': 169.0,
  'player_of_match': 'JC Buttler'},
 {'match_id': 1178402,
  'season': 2019,
  'date': '2019-04-13',
  'match_type': 'League',
  'city': 'Mumbai',
  'venue': 'Wankhede Stadium',
  'toss_winner': 'Rajasthan Royals',
  'toss_decision': 'field',
  'winner': 'Rajasthan Royals',
  'target_runs': 188.0,
  'player_of_match': 'JC Buttler'},
 {'match_id': 1178411,
  'season': 2019,
  'date': '2019-04-20',
  'match_type': 'League',
  'city': 'Jaipur',
  'venue': 'Sawai Mansingh Stadium',
  'toss_winner': 'Rajasthan Royals',
  'toss_decision': 'field',
  'winner': 'Rajasthan Royals',
  'target_runs': 162.0,
  'player_of_match': 'SPD Smith'},
 {'match_id': 1216511,
  'season': 2020,
  'date': '2020-10-06',
  'match_type': 'League',
  'city': 'Abu Dhabi',
  'venue': 'Sheikh Zayed Stadium',
  'toss_winner': 'Mumbai Indians',
  'toss_decision': 'bat',
  'winner': 'Mumbai Indians',
  'target_runs': 194.0,
  'player_of_match': 'SA Yadav'},
 {'match_id': 1216541,
  'season': 2020,
  'date': '2020-10-25',
  'match_type': 'League',
  'city': 'Abu Dhabi',
  'venue': 'Sheikh Zayed Stadium',
  'toss_winner': 'Mumbai Indians',
  'toss_decision': 'bat',
  'winner': 'Rajasthan Royals',
  'target_runs': 196.0,
  'player_of_match': 'BA Stokes'},
 {'match_id': 1254081,
  'season': 2021,
  'date': '2021-04-29',
  'match_type': 'League',
  'city': 'Delhi',
  'venue': 'Arun Jaitley Stadium',
  'toss_winner': 'Mumbai Indians',
  'toss_decision': 'field',
  'winner': 'Mumbai Indians',
  'target_runs': 172.0,
  'player_of_match': 'Q de Kock'},
 {'match_id': 1254093,
  'season': 2021,
  'date': '2021-10-05',
  'match_type': 'League',
  'city': 'Sharjah',
  'venue': 'Sharjah Cricket Stadium',
  'toss_winner': 'Mumbai Indians',
  'toss_decision': 'field',
  'winner': 'Mumbai Indians',
  'target_runs': 91.0,
  'player_of_match': 'NM Coulter-Nile'},
 {'match_id': 1304055,
  'season': 2022,
  'date': '2022-04-02',
  'match_type': 'League',
  'city': 'Mumbai',
  'venue': 'Dr DY Patil Sports Academy',
  'toss_winner': 'Mumbai Indians',
  'toss_decision': 'field',
  'winner': 'Rajasthan Royals',
  'target_runs': 194.0,
  'player_of_match': 'JC Buttler'},
 {'match_id': 1304090,
  'season': 2022,
  'date': '2022-04-30',
  'match_type': 'League',
  'city': 'Mumbai',
  'venue': 'Dr DY Patil Sports Academy',
  'toss_winner': 'Mumbai Indians',
  'toss_decision': 'field',
  'winner': 'Mumbai Indians',
  'target_runs': 159.0,
  'player_of_match': 'SA Yadav'},
 {'match_id': 1359516,
  'season': 2023,
  'date': '2023-04-30',
  'match_type': 'League',
  'city': 'Mumbai',
  'venue': 'Wankhede Stadium',
  'toss_winner': 'Rajasthan Royals',
  'toss_decision': 'bat',
  'winner': 'Mumbai Indians',
  'target_runs': 213.0,
  'player_of_match': 'YBK Jaiswal'},
 {'match_id': 1422132,
  'season': 2024,
  'date': '2024-04-01',
  'match_type': 'League',
  'city': 'Mumbai',
  'venue': 'Wankhede Stadium',
  'toss_winner': 'Rajasthan Royals',
  'toss_decision': 'field',
  'winner': 'Rajasthan Royals',
  'target_runs': 126.0,
  'player_of_match': 'TA Boult'},
 {'match_id': 1426276,
  'season': 2024,
  'date': '2024-04-22',
  'match_type': 'League',
  'city': 'Jaipur',
  'venue': 'Sawai Mansingh Stadium',
  'toss_winner': 'Mumbai Indians',
  'toss_decision': 'bat',
  'winner': 'Rajasthan Royals',
  'target_runs': 180.0,
  'player_of_match': 'Sandeep Sharma'},
 {'total_matches': 29},
 {'wins_of_team1': 14},
 {'wins_of_team2': 15},
 {'winning_rate_team1': 48.28},
 {'winning_rate_team2': 51.72}]

In [51]:
def HTH_Overall(team1, team2):
    # Extracting data with respect to teams
    matches = ipl2[((ipl2['team1'] == team1) & (ipl2['team2'] == team2)) |
                   ((ipl2['team2'] == team1) & (ipl2['team1'] == team2))]

    # Checking if there are any matches
    if not matches.empty:
        # Fetching the required columns to return
        records = matches[['match_id', 'season', 'date', 'match_type', 'city', 'venue', 
                           'toss_winner', 'toss_decision', 'winner', 'target_runs', 'player_of_match']]
        
        # Number of matches they played against
        total_matches = records.shape[0]

        # Number of wins for each team
        team1_win = records[records['winner'] == team1].shape[0]
        team2_win = records[records['winner'] == team2].shape[0]

        # Winning percentages
        winning_rate_team1 = (team1_win / total_matches) * 100
        winning_rate_team2 = (team2_win / total_matches) * 100

        # Creating the result dictionary
        result = {
            'match_records': json.loads(records.to_json(orient='records')),
            'summary': {
                'total_matches': total_matches,
                'wins_of_team1': team1_win,
                'wins_of_team2': team2_win,
                'winning_rate_team1': round(winning_rate_team1, 2),
                'winning_rate_team2': round(winning_rate_team2, 2)
            }
        }
        return result
    else:
        return {'error': 'Data not available'}

In [52]:
HTH_Overall('Rajasthan Royals','Mumbai Indians')

{'match_records': [{'match_id': 336008,
   'season': 2008,
   'date': '2008-05-07',
   'match_type': 'League',
   'city': 'Mumbai',
   'venue': 'Dr DY Patil Sports Academy',
   'toss_winner': 'Mumbai Indians',
   'toss_decision': 'field',
   'winner': 'Mumbai Indians',
   'target_runs': 104.0,
   'player_of_match': 'A Nehra'},
  {'match_id': 336036,
   'season': 2008,
   'date': '2008-05-26',
   'match_type': 'League',
   'city': 'Jaipur',
   'venue': 'Sawai Mansingh Stadium',
   'toss_winner': 'Rajasthan Royals',
   'toss_decision': 'field',
   'winner': 'Rajasthan Royals',
   'target_runs': 146.0,
   'player_of_match': 'Sohail Tanvir'},
  {'match_id': 392225,
   'season': 2009,
   'date': '2009-05-14',
   'match_type': 'League',
   'city': 'Durban',
   'venue': 'Kingsmead',
   'toss_winner': 'Rajasthan Royals',
   'toss_decision': 'bat',
   'winner': 'Rajasthan Royals',
   'target_runs': 146.0,
   'player_of_match': 'SK Warne'},
  {'match_id': 419107,
   'season': 2010,
   'date': '2010-03-13',
   'match_type': 'League',
   'city': 'Mumbai',
   'venue': 'Brabourne Stadium',
   'toss_winner': 'Mumbai Indians',
   'toss_decision': 'bat',
   'winner': 'Mumbai Indians',
   'target_runs': 213.0,
   'player_of_match': 'YK Pathan'},
  {'match_id': 419150,
   'season': 2010,
   'date': '2010-04-11',
   'match_type': 'League',
   'city': 'Jaipur',
   'venue': 'Sawai Mansingh Stadium',
   'toss_winner': 'Rajasthan Royals',
   'toss_decision': 'field',
   'winner': 'Mumbai Indians',
   'target_runs': 175.0,
   'player_of_match': 'SR Tendulkar'},
  {'match_id': 501231,
   'season': 2011,
   'date': '2011-04-29',
   'match_type': 'League',
   'city': 'Jaipur',
   'venue': 'Sawai Mansingh Stadium',
   'toss_winner': 'Rajasthan Royals',
   'toss_decision': 'field',
   'winner': 'Rajasthan Royals',
   'target_runs': 95.0,
   'player_of_match': 'J Botha'},
  {'match_id': 501263,
   'season': 2011,
   'date': '2011-05-20',
   'match_type': 'League',
   'city': 'Mumbai',
   'venue': 'Wankhede Stadium',
   'toss_winner': 'Mumbai Indians',
   'toss_decision': 'bat',
   'winner': 'Rajasthan Royals',
   'target_runs': 134.0,
   'player_of_match': 'SR Watson'},
  {'match_id': 548317,
   'season': 2012,
   'date': '2012-04-11',
   'match_type': 'League',
   'city': 'Mumbai',
   'venue': 'Wankhede Stadium',
   'toss_winner': 'Rajasthan Royals',
   'toss_decision': 'field',
   'winner': 'Mumbai Indians',
   'target_runs': 198.0,
   'player_of_match': 'KA Pollard'},
  {'match_id': 548377,
   'season': 2012,
   'date': '2012-05-20',
   'match_type': 'League',
   'city': 'Jaipur',
   'venue': 'Sawai Mansingh Stadium',
   'toss_winner': 'Rajasthan Royals',
   'toss_decision': 'bat',
   'winner': 'Mumbai Indians',
   'target_runs': 163.0,
   'player_of_match': 'DR Smith'},
  {'match_id': 598019,
   'season': 2013,
   'date': '2013-04-17',
   'match_type': 'League',
   'city': 'Jaipur',
   'venue': 'Sawai Mansingh Stadium',
   'toss_winner': 'Rajasthan Royals',
   'toss_decision': 'bat',
   'winner': 'Rajasthan Royals',
   'target_runs': 180.0,
   'player_of_match': 'AM Rahane'},
  {'match_id': 598063,
   'season': 2013,
   'date': '2013-05-15',
   'match_type': 'League',
   'city': 'Mumbai',
   'venue': 'Wankhede Stadium',
   'toss_winner': 'Rajasthan Royals',
   'toss_decision': 'field',
   'winner': 'Mumbai Indians',
   'target_runs': 167.0,
   'player_of_match': 'AP Tare'},
  {'match_id': 598072,
   'season': 2013,
   'date': '2013-05-24',
   'match_type': 'Qualifier 2',
   'city': 'Kolkata',
   'venue': 'Eden Gardens',
   'toss_winner': 'Rajasthan Royals',
   'toss_decision': 'bat',
   'winner': 'Mumbai Indians',
   'target_runs': 166.0,
   'player_of_match': 'Harbhajan Singh'},
  {'match_id': 734017,
   'season': 2014,
   'date': '2014-05-19',
   'match_type': 'League',
   'city': 'Ahmedabad',
   'venue': 'Sardar Patel Stadium, Motera',
   'toss_winner': 'Mumbai Indians',
   'toss_decision': 'bat',
   'winner': 'Mumbai Indians',
   'target_runs': 179.0,
   'player_of_match': 'MEK Hussey'},
  {'match_id': 734041,
   'season': 2014,
   'date': '2014-05-25',
   'match_type': 'League',
   'city': 'Mumbai',
   'venue': 'Wankhede Stadium',
   'toss_winner': 'Mumbai Indians',
   'toss_decision': 'field',
   'winner': 'Mumbai Indians',
   'target_runs': 190.0,
   'player_of_match': 'CJ Anderson'},
  {'match_id': 829721,
   'season': 2015,
   'date': '2015-04-14',
   'match_type': 'League',
   'city': 'Ahmedabad',
   'venue': 'Sardar Patel Stadium, Motera',
   'toss_winner': 'Mumbai Indians',
   'toss_decision': 'bat',
   'winner': 'Rajasthan Royals',
   'target_runs': 165.0,
   'player_of_match': 'SPD Smith'},
  {'match_id': 829769,
   'season': 2015,
   'date': '2015-05-01',
   'match_type': 'League',
   'city': 'Mumbai',
   'venue': 'Wankhede Stadium',
   'toss_winner': 'Rajasthan Royals',
   'toss_decision': 'field',
   'winner': 'Mumbai Indians',
   'target_runs': 188.0,
   'player_of_match': 'AT Rayudu'},
  {'match_id': 1136581,
   'season': 2018,
   'date': '2018-04-22',
   'match_type': 'League',
   'city': 'Jaipur',
   'venue': 'Sawai Mansingh Stadium',
   'toss_winner': 'Mumbai Indians',
   'toss_decision': 'bat',
   'winner': 'Rajasthan Royals',
   'target_runs': 168.0,
   'player_of_match': 'JC Archer'},
  {'match_id': 1136607,
   'season': 2018,
   'date': '2018-05-13',
   'match_type': 'League',
   'city': 'Mumbai',
   'venue': 'Wankhede Stadium',
   'toss_winner': 'Rajasthan Royals',
   'toss_decision': 'field',
   'winner': 'Rajasthan Royals',
   'target_runs': 169.0,
   'player_of_match': 'JC Buttler'},
  {'match_id': 1178402,
   'season': 2019,
   'date': '2019-04-13',
   'match_type': 'League',
   'city': 'Mumbai',
   'venue': 'Wankhede Stadium',
   'toss_winner': 'Rajasthan Royals',
   'toss_decision': 'field',
   'winner': 'Rajasthan Royals',
   'target_runs': 188.0,
   'player_of_match': 'JC Buttler'},
  {'match_id': 1178411,
   'season': 2019,
   'date': '2019-04-20',
   'match_type': 'League',
   'city': 'Jaipur',
   'venue': 'Sawai Mansingh Stadium',
   'toss_winner': 'Rajasthan Royals',
   'toss_decision': 'field',
   'winner': 'Rajasthan Royals',
   'target_runs': 162.0,
   'player_of_match': 'SPD Smith'},
  {'match_id': 1216511,
   'season': 2020,
   'date': '2020-10-06',
   'match_type': 'League',
   'city': 'Abu Dhabi',
   'venue': 'Sheikh Zayed Stadium',
   'toss_winner': 'Mumbai Indians',
   'toss_decision': 'bat',
   'winner': 'Mumbai Indians',
   'target_runs': 194.0,
   'player_of_match': 'SA Yadav'},
  {'match_id': 1216541,
   'season': 2020,
   'date': '2020-10-25',
   'match_type': 'League',
   'city': 'Abu Dhabi',
   'venue': 'Sheikh Zayed Stadium',
   'toss_winner': 'Mumbai Indians',
   'toss_decision': 'bat',
   'winner': 'Rajasthan Royals',
   'target_runs': 196.0,
   'player_of_match': 'BA Stokes'},
  {'match_id': 1254081,
   'season': 2021,
   'date': '2021-04-29',
   'match_type': 'League',
   'city': 'Delhi',
   'venue': 'Arun Jaitley Stadium',
   'toss_winner': 'Mumbai Indians',
   'toss_decision': 'field',
   'winner': 'Mumbai Indians',
   'target_runs': 172.0,
   'player_of_match': 'Q de Kock'},
  {'match_id': 1254093,
   'season': 2021,
   'date': '2021-10-05',
   'match_type': 'League',
   'city': 'Sharjah',
   'venue': 'Sharjah Cricket Stadium',
   'toss_winner': 'Mumbai Indians',
   'toss_decision': 'field',
   'winner': 'Mumbai Indians',
   'target_runs': 91.0,
   'player_of_match': 'NM Coulter-Nile'},
  {'match_id': 1304055,
   'season': 2022,
   'date': '2022-04-02',
   'match_type': 'League',
   'city': 'Mumbai',
   'venue': 'Dr DY Patil Sports Academy',
   'toss_winner': 'Mumbai Indians',
   'toss_decision': 'field',
   'winner': 'Rajasthan Royals',
   'target_runs': 194.0,
   'player_of_match': 'JC Buttler'},
  {'match_id': 1304090,
   'season': 2022,
   'date': '2022-04-30',
   'match_type': 'League',
   'city': 'Mumbai',
   'venue': 'Dr DY Patil Sports Academy',
   'toss_winner': 'Mumbai Indians',
   'toss_decision': 'field',
   'winner': 'Mumbai Indians',
   'target_runs': 159.0,
   'player_of_match': 'SA Yadav'},
  {'match_id': 1359516,
   'season': 2023,
   'date': '2023-04-30',
   'match_type': 'League',
   'city': 'Mumbai',
   'venue': 'Wankhede Stadium',
   'toss_winner': 'Rajasthan Royals',
   'toss_decision': 'bat',
   'winner': 'Mumbai Indians',
   'target_runs': 213.0,
   'player_of_match': 'YBK Jaiswal'},
  {'match_id': 1422132,
   'season': 2024,
   'date': '2024-04-01',
   'match_type': 'League',
   'city': 'Mumbai',
   'venue': 'Wankhede Stadium',
   'toss_winner': 'Rajasthan Royals',
   'toss_decision': 'field',
   'winner': 'Rajasthan Royals',
   'target_runs': 126.0,
   'player_of_match': 'TA Boult'},
  {'match_id': 1426276,
   'season': 2024,
   'date': '2024-04-22',
   'match_type': 'League',
   'city': 'Jaipur',
   'venue': 'Sawai Mansingh Stadium',
   'toss_winner': 'Mumbai Indians',
   'toss_decision': 'bat',
   'winner': 'Rajasthan Royals',
   'target_runs': 180.0,
   'player_of_match': 'Sandeep Sharma'}],
 'summary': {'total_matches': 29,
  'wins_of_team1': 14,
  'wins_of_team2': 15,
  'winning_rate_team1': 48.28,
  'winning_rate_team2': 51.72}}

3) Toss Analysis:
- this will return the analysis of toss wins, toss decisions, winning rate after winning toss.

In [54]:
def toss_analysis():
    """
    Analyzes toss decisions in IPL matches and computes statistics.
    Returns:
        dict: A dictionary containing percentages of toss decisions and their outcomes.
    """

    # Fetching details
    toss_bat = ipl2[ipl2['toss_decision'] == 'bat']
    toss_field = ipl2[ipl2['toss_decision'] == 'field']
    win_toss_match = ipl2[ipl2['toss_winner'] == ipl2['winner']].shape[0]
    win_bat_match = toss_bat[toss_bat['winner'] == toss_bat['toss_winner']].shape[0]
    win_field_match = toss_field[toss_field['winner'] == toss_field['toss_winner']].shape[0]

    # Converting to percentages
    rate_toss_bat = (toss_bat.shape[0] / ipl2.shape[0]) * 100
    rate_toss_field = (toss_field.shape[0] / ipl2.shape[0]) * 100
    rate_win_toss_match = (win_toss_match / ipl2.shape[0]) * 100
    rate_win_bat_match = (win_bat_match / toss_bat.shape[0] * 100) if toss_bat.shape[0] > 0 else 0
    rate_win_field_match = (win_field_match / toss_field.shape[0] * 100) if toss_field.shape[0] > 0 else 0

    # Preparing the response
    response = {
        'toss_bat_percentage': round(rate_toss_bat, 2),
        'toss_field_percentage': round(rate_toss_field, 2),
        'win_toss_match_percentage': round(rate_win_toss_match, 2),
        'bat_after_toss_win_percentage': round(rate_win_bat_match, 2),
        'field_after_toss_win_percentage': round(rate_win_field_match, 2),
    }

    return response

In [55]:
toss_analysis()

{'toss_bat_percentage': 35.71,
 'toss_field_percentage': 64.29,
 'win_toss_match_percentage': 50.59,
 'bat_after_toss_win_percentage': 45.27,
 'field_after_toss_win_percentage': 53.55}

## C) Players API

# 1. Player Performance
- gives overall players performance like total runs, ball faced, strike rate, boundaries, wickets, man of the match, Number of matches played, plays as

In [58]:
def players_performance(name):
    records1 = ipl1[ipl1['batter'] == name]
    records2 = ipl1[ipl1['bowler'] == name]
    records3 = ipl1[ipl1['fielder'] == name]
    plays_as = []

    # Initialize variables
    total_runs = 0
    min_score = 0
    max_score = 0
    avg_score = 0
    num_ball = 0
    boundary_4 = 0
    boundary_6 = 0
    strike_rate = 0
    wickets_taken = 0

    if not records1.empty:
        plays_as.append('batter')
        total_runs = records1['batsman_runs'].sum()
        min_score = records1.groupby('match_id')['batsman_runs'].sum().min()
        max_score = records1.groupby('match_id')['batsman_runs'].sum().max()
        avg_score = records1.groupby('match_id')['batsman_runs'].sum().mean()
        num_ball = records1['ball'].count()
        boundary_4 = records1[records1['batsman_runs'] == 4].shape[0]
        boundary_6 = records1[records1['batsman_runs'] == 6].shape[0]
        strike_rate = round((total_runs / num_ball) * 100, 2) if num_ball > 0 else 0

    if not records2.empty:
        plays_as.append('bowler')
        wickets_taken = records2[records2['is_wicket'] == 1].shape[0]

    if not records3.empty:
        plays_as.append('fielder')

    # Combine records to get matches played
    all_records = pd.concat([records1, records2, records3])
    matches_played = all_records['match_id'].nunique()

    # Get unique teams played for
    teams_played = pd.concat([
        records1['batting_team'], 
        records2['bowling_team'], 
        records3['bowling_team']
    ]).unique().tolist()

    # Number of times player was "Player of the Match"
    num_man_of_match = ipl2[ipl2['player_of_match'] == name].shape[0]

    response = {
        'teams_played': teams_played,
        'played_as': plays_as,
        'number_matches': matches_played,
        'total_runs': total_runs,
        'num_ball': num_ball,
        'highest_score': max_score,
        'lowest_score': min_score,
        'average_score': round(avg_score, 2),
        'boundaries_4': boundary_4,
         'boundaries_6': boundary_6,
        'strike_rate': strike_rate,
        'wickets_taken': wickets_taken,
        'player_of_match': num_man_of_match
        }
    return response

In [59]:
players_performance('V Kohli')

{'teams_played': ['Royal Challengers Bangalore'],
 'played_as': ['batter', 'bowler', 'fielder'],
 'number_matches': 247,
 'total_runs': 8014,
 'num_ball': 6236,
 'highest_score': 113,
 'lowest_score': 0,
 'average_score': 32.84,
 'boundaries_4': 708,
 'boundaries_6': 273,
 'strike_rate': 128.51,
 'wickets_taken': 5,
 'player_of_match': 18}

# 2) Top players
- players List according to batting and bowling a descending list based on their strike rate and wickets

In [61]:
def top_players(player):
    if player == 'batter':
        # Grouping by batter to calculate runs and balls faced
        runs = ipl1.groupby('batter')['batsman_runs'].sum()
        balls = ipl1.groupby('batter')['ball'].count()
        
        # Calculating strike rate
        strike_rate = round((runs / balls) * 100, 2)
        
        # Creating a DataFrame
        batter_stats = pd.DataFrame({'runs': runs, 'balls': balls, 'strike_rate': strike_rate})
        
        # Filtering players who faced more than 20 balls
        filtered_batters = batter_stats[batter_stats['balls'] > 20]
        
        # Sorting by strike rate in descending order
        sorted_batters = filtered_batters.sort_values(by='strike_rate', ascending=False)
        
        # Creating a dictionary with player names as keys
        response = sorted_batters.to_dict(orient='index')
        
        return {name: details for name, details in response.items()}
    
    elif player == 'bowler':
        # Grouping by bowler to calculate balls bowled
        balls = ipl1.groupby('bowler')['ball'].count()
        
        # Filtering only dismissals (is_wicket == 1) and grouping by bowler
        wickets = ipl1[ipl1['is_wicket'] == 1].groupby('bowler')['is_wicket'].count()
        
        # Creating a DataFrame for bowlers
        bowler_stats = pd.DataFrame({'balls': balls, 'wickets': wickets}).fillna(0)
        
        # Filtering bowlers who have taken at least 1 wicket
        filtered_bowlers = bowler_stats[bowler_stats['wickets'] > 0]
        
        # Sorting by wickets taken in descending order
        sorted_bowlers = filtered_bowlers.sort_values(by='wickets', ascending=False)
        
        # Creating a dictionary with player names as keys
        response = sorted_bowlers.to_dict(orient='index')
        
        return {name: details for name, details in response.items()}

    else:
        return {'error': 'Invalid player type. Please use "batter" or "bowler".'}

In [62]:
top_players('bowler')

{'YS Chahal': {'balls': 3628, 'wickets': 213.0},
 'DJ Bravo': {'balls': 3296, 'wickets': 207.0},
 'PP Chawla': {'balls': 3895, 'wickets': 201.0},
 'SP Narine': {'balls': 4146, 'wickets': 200.0},
 'R Ashwin': {'balls': 4679, 'wickets': 198.0},
 'B Kumar': {'balls': 4060, 'wickets': 195.0},
 'SL Malinga': {'balls': 2974, 'wickets': 188.0},
 'A Mishra': {'balls': 3444, 'wickets': 183.0},
 'JJ Bumrah': {'balls': 3185, 'wickets': 182.0},
 'RA Jadeja': {'balls': 3895, 'wickets': 169.0},
 'UT Yadav': {'balls': 3190, 'wickets': 163.0},
 'Harbhajan Singh': {'balls': 3496, 'wickets': 161.0},
 'Rashid Khan': {'balls': 2901, 'wickets': 157.0},
 'Sandeep Sharma': {'balls': 2925, 'wickets': 153.0},
 'HV Patel': {'balls': 2284, 'wickets': 151.0},
 'MM Sharma': {'balls': 2308, 'wickets': 147.0},
 'Mohammed Shami': {'balls': 2521, 'wickets': 144.0},
 'AR Patel': {'balls': 3152, 'wickets': 131.0},
 'TA Boult': {'balls': 2428, 'wickets': 128.0},
 'R Vinay Kumar': {'balls': 2186, 'wickets': 127.0},
 'K Rabada': {'balls': 1907, 'wickets': 126.0},
 'AD Russell': {'balls': 1771, 'wickets': 125.0},
 'A Nehra': {'balls': 1974, 'wickets': 121.0},
 'Z Khan': {'balls': 2276, 'wickets': 119.0},
 'JD Unadkat': {'balls': 2194, 'wickets': 109.0},
 'SR Watson': {'balls': 2137, 'wickets': 107.0},
 'CH Morris': {'balls': 1801, 'wickets': 107.0},
 'DW Steyn': {'balls': 2282, 'wickets': 105.0},
 'P Kumar': {'balls': 2637, 'wickets': 102.0},
 'SN Thakur': {'balls': 1979, 'wickets': 100.0},
 'RP Singh': {'balls': 1874, 'wickets': 100.0},
 'PP Ojha': {'balls': 1945, 'wickets': 99.0},
 'IK Pathan': {'balls': 2113, 'wickets': 99.0},
 'I Sharma': {'balls': 2429, 'wickets': 96.0},
 'JA Morkel': {'balls': 1807, 'wickets': 96.0},
 'Mohammed Siraj': {'balls': 2081, 'wickets': 96.0},
 'DS Kulkarni': {'balls': 1876, 'wickets': 91.0},
 'Kuldeep Yadav': {'balls': 1786, 'wickets': 90.0},
 'M Morkel': {'balls': 1699, 'wickets': 88.0},
 'Imran Tahir': {'balls': 1340, 'wickets': 86.0},
 'CV Varun': {'balls': 1624, 'wickets': 85.0},
 'L Balaji': {'balls': 1574, 'wickets': 85.0},
 'Arshdeep Singh': {'balls': 1453, 'wickets': 84.0},
 'R Bhatia': {'balls': 1661, 'wickets': 82.0},
 'AB Dinda': {'balls': 1589, 'wickets': 82.0},
 'KV Sharma': {'balls': 1520, 'wickets': 82.0},
 'MM Patel': {'balls': 1382, 'wickets': 82.0},
 'Avesh Khan': {'balls': 1390, 'wickets': 81.0},
 'KA Pollard': {'balls': 1586, 'wickets': 81.0},
 'KH Pandya': {'balls': 2183, 'wickets': 80.0},
 'DL Chahar': {'balls': 1746, 'wickets': 79.0},
 'KK Ahmed': {'balls': 1345, 'wickets': 78.0},
 'JP Faulkner': {'balls': 1287, 'wickets': 76.0},
 'RD Chahar': {'balls': 1697, 'wickets': 76.0},
 'T Natarajan': {'balls': 1401, 'wickets': 76.0},
 'MJ McClenaghan': {'balls': 1346, 'wickets': 75.0},
 'JH Kallis': {'balls': 1799, 'wickets': 74.0},
 'SK Trivedi': {'balls': 1557, 'wickets': 73.0},
 'Shakib Al Hasan': {'balls': 1515, 'wickets': 71.0},
 'Mustafizur Rahman': {'balls': 1353, 'wickets': 70.0},
 'HH Pandya': {'balls': 1485, 'wickets': 70.0},
 'Ravi Bishnoi': {'balls': 1460, 'wickets': 68.0},
 'M Muralitharan': {'balls': 1581, 'wickets': 67.0},
 'MG Johnson': {'balls': 1301, 'wickets': 66.0},
 'PJ Cummins': {'balls': 1370, 'wickets': 66.0},
 'S Kaul': {'balls': 1238, 'wickets': 63.0},
 'SM Curran': {'balls': 1234, 'wickets': 62.0},
 'A Nortje': {'balls': 1097, 'wickets': 62.0},
 'SK Warne': {'balls': 1223, 'wickets': 60.0},
 'MA Starc': {'balls': 879, 'wickets': 59.0},
 'JO Holder': {'balls': 1049, 'wickets': 59.0},
 'TG Southee': {'balls': 1262, 'wickets': 57.0},
 'LH Ferguson': {'balls': 1002, 'wickets': 57.0},
 'S Nadeem': {'balls': 1444, 'wickets': 54.0},
 'M Prasidh Krishna': {'balls': 1231, 'wickets': 54.0},
 'S Gopal': {'balls': 1000, 'wickets': 53.0},
 'NM Coulter-Nile': {'balls': 892, 'wickets': 52.0},
 'SB Jakati': {'balls': 1101, 'wickets': 50.0},
 'JC Archer': {'balls': 987, 'wickets': 49.0},
 'A Kumble': {'balls': 983, 'wickets': 49.0},
 'AJ Tye': {'balls': 714, 'wickets': 48.0},
 'S Aravind': {'balls': 788, 'wickets': 48.0},
 'RJ Harris': {'balls': 865, 'wickets': 47.0},
 'YK Pathan': {'balls': 1184, 'wickets': 46.0},
 'VR Aaron': {'balls': 1065, 'wickets': 46.0},
 'MC Henriques': {'balls': 979, 'wickets': 46.0},
 'TU Deshpande': {'balls': 831, 'wickets': 46.0},
 'MP Stoinis': {'balls': 831, 'wickets': 45.0},
 'Iqbal Abdulla': {'balls': 943, 'wickets': 45.0},
 'PJ Sangwan': {'balls': 905, 'wickets': 44.0},
 'S Sreesanth': {'balls': 947, 'wickets': 43.0},
 'DE Bollinger': {'balls': 600, 'wickets': 43.0},
 'P Awana': {'balls': 774, 'wickets': 43.0},
 'R Sharma': {'balls': 935, 'wickets': 42.0},
 'GJ Maxwell': {'balls': 965, 'wickets': 41.0},
 'MM Ali': {'balls': 770, 'wickets': 40.0},
 'WD Parnell': {'balls': 758, 'wickets': 40.0},
 'DT Christian': {'balls': 922, 'wickets': 40.0},
 'Yuvraj Singh': {'balls': 882, 'wickets': 39.0},
 'MS Gony': {'balls': 925, 'wickets': 39.0},
 'Washington Sundar': {'balls': 1064, 'wickets': 39.0},
 'M Kartik': {'balls': 1182, 'wickets': 39.0},
 'DP Nannes': {'balls': 689, 'wickets': 38.0},
 'M Pathirana': {'balls': 503, 'wickets': 38.0},
 'P Negi': {'balls': 733, 'wickets': 38.0},
 'M Markande': {'balls': 737, 'wickets': 37.0},
 'MR Marsh': {'balls': 593, 'wickets': 37.0},
 'NLTC Perera': {'balls': 715, 'wickets': 37.0},
 'JR Hazlewood': {'balls': 622, 'wickets': 36.0},
 'CJ Jordan': {'balls': 717, 'wickets': 36.0},
 'KK Cooper': {'balls': 600, 'wickets': 36.0},
 'PWH de Silva': {'balls': 557, 'wickets': 36.0},
 'R Tewatia': {'balls': 866, 'wickets': 36.0},
 'M Ashwin': {'balls': 898, 'wickets': 35.0},
 'DL Vettori': {'balls': 785, 'wickets': 34.0},
 'MF Maharoof': {'balls': 441, 'wickets': 33.0},
 'AB Agarkar': {'balls': 820, 'wickets': 33.0},
 'Shivam Mavi': {'balls': 687, 'wickets': 33.0},
 'A Singh': {'balls': 486, 'wickets': 31.0},
 'CR Woakes': {'balls': 463, 'wickets': 31.0},
 'BA Stokes': {'balls': 723, 'wickets': 31.0},
 'Mukesh Kumar': {'balls': 420, 'wickets': 31.0},
 'Azhar Mahmood': {'balls': 552, 'wickets': 31.0},
 'Harmeet Singh': {'balls': 574, 'wickets': 31.0},
 'Umran Malik': {'balls': 519, 'wickets': 31.0},
 'Yash Dayal': {'balls': 615, 'wickets': 31.0},
 'A Zampa': {'balls': 425, 'wickets': 30.0},
 'SK Raina': {'balls': 930, 'wickets': 30.0},
 'B Lee': {'balls': 916, 'wickets': 30.0},
 'STR Binny': {'balls': 611, 'wickets': 28.0},
 'L Ngidi': {'balls': 342, 'wickets': 28.0},
 'AD Mathews': {'balls': 807, 'wickets': 28.0},
 'PV Tambe': {'balls': 674, 'wickets': 28.0},
 'Mohsin Khan': {'balls': 507, 'wickets': 27.0},
 'R Dhawan': {'balls': 693, 'wickets': 27.0},
 'Yash Thakur': {'balls': 432, 'wickets': 27.0},
 'Harshit Rana': {'balls': 403, 'wickets': 27.0},
 'J Botha': {'balls': 709, 'wickets': 27.0},
 'DR Smith': {'balls': 557, 'wickets': 27.0},
 'Naveen-ul-Haq': {'balls': 407, 'wickets': 26.0},
 'Navdeep Saini': {'balls': 682, 'wickets': 26.0},
 'Basil Thampi': {'balls': 539, 'wickets': 26.0},
 'SW Tait': {'balls': 534, 'wickets': 26.0},
 'M Theekshana': {'balls': 631, 'wickets': 25.0},
 'Harpreet Brar': {'balls': 692, 'wickets': 25.0},
 'GB Hogg': {'balls': 466, 'wickets': 25.0},
 'RE van der Merwe': {'balls': 455, 'wickets': 25.0},
 'AS Rajpoot': {'balls': 567, 'wickets': 24.0},
 'Noor Ahmad': {'balls': 513, 'wickets': 24.0},
 'Sohail Tanvir': {'balls': 265, 'wickets': 24.0},
 'BW Hilfenhaus': {'balls': 390, 'wickets': 23.0},
 'A Symonds': {'balls': 540, 'wickets': 23.0},
 'JP Duminy': {'balls': 701, 'wickets': 23.0},
 'Akash Madhwal': {'balls': 279, 'wickets': 22.0},
 'K Gowtham': {'balls': 599, 'wickets': 22.0},
 'M Jansen': {'balls': 487, 'wickets': 22.0},
 'Bipul Sharma': {'balls': 436, 'wickets': 22.0},
 'AS Joseph': {'balls': 454, 'wickets': 22.0},
 'VY Mahesh': {'balls': 359, 'wickets': 22.0},
 'WPUJC Vaas': {'balls': 288, 'wickets': 22.0},
 'JP Behrendorff': {'balls': 379, 'wickets': 22.0},
 'RP Meredith': {'balls': 415, 'wickets': 21.0},
 'Anureet Singh': {'balls': 430, 'wickets': 21.0},
 'KW Richardson': {'balls': 345, 'wickets': 21.0},
 'Shahbaz Ahmed': {'balls': 549, 'wickets': 21.0},
 'BB Sran': {'balls': 516, 'wickets': 20.0},
 'J Suchith': {'balls': 434, 'wickets': 20.0},
 'Mujeeb Ur Rahman': {'balls': 452, 'wickets': 20.0},
 'C Green': {'balls': 462, 'wickets': 20.0},
 'VG Arora': {'balls': 418, 'wickets': 20.0},
 'C Sakariya': {'balls': 460, 'wickets': 20.0},
 'CH Gayle': {'balls': 584, 'wickets': 19.0},
 'NT Ellis': {'balls': 365, 'wickets': 19.0},
 'CRD Fernando': {'balls': 249, 'wickets': 19.0},
 'AD Mascarenhas': {'balls': 310, 'wickets': 19.0},
 'A Ashish Reddy': {'balls': 270, 'wickets': 19.0},
 'IC Pandey': {'balls': 469, 'wickets': 19.0},
 'BJ Hodge': {'balls': 238, 'wickets': 18.0},
 'R Rampaul': {'balls': 278, 'wickets': 17.0},
 'Vijaykumar Vyshak': {'balls': 243, 'wickets': 17.0},
 'D Wiese': {'balls': 307, 'wickets': 17.0},
 'LR Shukla': {'balls': 326, 'wickets': 17.0},
 'Mukesh Choudhary': {'balls': 298, 'wickets': 16.0},
 'AC Thomas': {'balls': 327, 'wickets': 16.0},
 'ST Jayasuriya': {'balls': 301, 'wickets': 16.0},
 'MJ Santner': {'balls': 370, 'wickets': 16.0},
 'Kartik Tyagi': {'balls': 458, 'wickets': 16.0},
 'VRV Singh': {'balls': 371, 'wickets': 16.0},
 'RG Sharma': {'balls': 349, 'wickets': 16.0},
 'CR Brathwaite': {'balls': 266, 'wickets': 16.0},
 'SJ Srivastava': {'balls': 306, 'wickets': 15.0},
 'YA Abdulla': {'balls': 222, 'wickets': 15.0},
 'RR Powar': {'balls': 443, 'wickets': 15.0},
 'AN Ahmed': {'balls': 362, 'wickets': 15.0},
 'DR Sams': {'balls': 389, 'wickets': 15.0},
 'Mohammad Nabi': {'balls': 419, 'wickets': 15.0},
 'KR Sen': {'balls': 255, 'wickets': 14.0},
 'JR Hopes': {'balls': 369, 'wickets': 14.0},
 'Umar Gul': {'balls': 153, 'wickets': 14.0},
 'Karanveer Singh': {'balls': 213, 'wickets': 14.0},
 'Kamran Khan': {'balls': 177, 'wickets': 14.0},
 'GD McGrath': {'balls': 329, 'wickets': 14.0},
 'S Lamichhane': {'balls': 211, 'wickets': 14.0},
 'AB McDonald': {'balls': 188, 'wickets': 14.0},
 'R McLaren': {'balls': 372, 'wickets': 14.0},
 'DJG Sammy': {'balls': 244, 'wickets': 14.0},
 'CJ Anderson': {'balls': 315, 'wickets': 14.0},
 'G Coetzee': {'balls': 216, 'wickets': 13.0},
 'JDP Oram': {'balls': 244, 'wickets': 13.0},
 'Joginder Sharma': {'balls': 272, 'wickets': 13.0},
 'J Theron': {'balls': 235, 'wickets': 13.0},
 'R Sai Kishore': {'balls': 191, 'wickets': 13.0},
 'CK Langeveldt': {'balls': 165, 'wickets': 13.0},
 'RS Bopara': {'balls': 213, 'wickets': 13.0},
 'SM Pollock': {'balls': 280, 'wickets': 13.0},
 'BA Bhatt': {'balls': 303, 'wickets': 13.0},
 'TK Curran': {'balls': 252, 'wickets': 13.0},
 'J Little': {'balls': 236, 'wickets': 13.0},
 'SC Ganguly': {'balls': 280, 'wickets': 12.0},
 'BCJ Cutting': {'balls': 288, 'wickets': 12.0},
 'AG Murtaza': {'balls': 269, 'wickets': 12.0},
 'Ankit Sharma': {'balls': 375, 'wickets': 12.0},
 'V Shankar': {'balls': 258, 'wickets': 12.0},
 'V Pratap Singh': {'balls': 211, 'wickets': 12.0},
 'Abhishek Sharma': {'balls': 278, 'wickets': 11.0},
 'OC McCoy': {'balls': 180, 'wickets': 11.0},
 'KP Appanna': {'balls': 222, 'wickets': 11.0},
 'Pankaj Singh': {'balls': 311, 'wickets': 11.0},
 'PVD Chameera': {'balls': 297, 'wickets': 11.0},
 'JL Pattinson': {'balls': 222, 'wickets': 11.0},
 'S Badree': {'balls': 263, 'wickets': 11.0},
 'MA Wood': {'balls': 127, 'wickets': 11.0},
 'BE Hendricks': {'balls': 157, 'wickets': 11.0},
 'A Chandila': {'balls': 234, 'wickets': 11.0},
 'LS Livingstone': {'balls': 267, 'wickets': 11.0},
 'Suyash Sharma': {'balls': 264, 'wickets': 11.0},
 'JD Ryder': {'balls': 241, 'wickets': 11.0},
 'Lalit Yadav': {'balls': 294, 'wickets': 11.0},
 'TS Mills': {'balls': 218, 'wickets': 11.0},
 'Simarjeet Singh': {'balls': 193, 'wickets': 10.0},
 'K Kartikeya': {'balls': 241, 'wickets': 10.0},
 'DJ Hussey': {'balls': 323, 'wickets': 10.0},
 'N Rana': {'balls': 185, 'wickets': 10.0},
 'KMA Paul': {'balls': 180, 'wickets': 10.0},
 'B Laughlin': {'balls': 179, 'wickets': 10.0},
 'MN Samuels': {'balls': 219, 'wickets': 10.0},
 'J Syed Mohammad': {'balls': 196, 'wickets': 10.0},
 'T Thushara': {'balls': 144, 'wickets': 10.0},
 'Anand Rajan': {'balls': 162, 'wickets': 10.0},
 'DJ Hooda': {'balls': 384, 'wickets': 10.0},
 'BAW Mendis': {'balls': 248, 'wickets': 9.0},
 'KA Jamieson': {'balls': 179, 'wickets': 9.0},
 'SE Bond': {'balls': 191, 'wickets': 9.0},
 'AF Milne': {'balls': 217, 'wickets': 9.0},
 'SMSM Senanayake': {'balls': 195, 'wickets': 9.0},
 'Mohammad Asif': {'balls': 199, 'wickets': 9.0},
 'AM Nayar': {'balls': 239, 'wickets': 9.0},
 'Shahid Afridi': {'balls': 185, 'wickets': 9.0},
 'KP Pietersen': {'balls': 180, 'wickets': 9.0},
 'Rasikh Salam': {'balls': 207, 'wickets': 9.0},
 'J Yadav': {'balls': 398, 'wickets': 9.0},
 'SB Styris': {'balls': 222, 'wickets': 9.0},
 'IS Sodhi': {'balls': 182, 'wickets': 9.0},
 'JEC Franklin': {'balls': 155, 'wickets': 9.0},
 'P Parameswaran': {'balls': 159, 'wickets': 9.0},
 'I Udana': {'balls': 182, 'wickets': 8.0},
 'N Thushara': {'balls': 172, 'wickets': 8.0},
 'S Sandeep Warrier': {'balls': 176, 'wickets': 8.0},
 'Akash Deep': {'balls': 175, 'wickets': 8.0},
 'S Randiv': {'balls': 180, 'wickets': 8.0},
 'A Mithun': {'balls': 312, 'wickets': 8.0},
 'GC Viljoen': {'balls': 146, 'wickets': 8.0},
 'MP Yadav': {'balls': 76, 'wickets': 8.0},
 'AA Chavan': {'balls': 255, 'wickets': 8.0},
 'M Ntini': {'balls': 213, 'wickets': 8.0},
 'JDS Neesham': {'balls': 222, 'wickets': 8.0},
 'KC Cariappa': {'balls': 224, 'wickets': 8.0},
 'AM Salvi': {'balls': 156, 'wickets': 7.0},
 'RR Raje': {'balls': 144, 'wickets': 7.0},
 'TL Suman': {'balls': 152, 'wickets': 7.0},
 'N Burger': {'balls': 105, 'wickets': 7.0},
 'B Akhil': {'balls': 193, 'wickets': 7.0},
 'PC Valthaty': {'balls': 153, 'wickets': 7.0},
 'Y Venugopal Rao': {'balls': 222, 'wickets': 7.0},
 'Swapnil Singh': {'balls': 165, 'wickets': 7.0},
 'D Pretorius': {'balls': 166, 'wickets': 7.0},
 'C de Grandhomme': {'balls': 230, 'wickets': 7.0},
 'R Shukla': {'balls': 130, 'wickets': 7.0},
 'P Amarnath': {'balls': 132, 'wickets': 7.0},
 'HF Gurney': {'balls': 169, 'wickets': 7.0},
 'KM Asif': {'balls': 143, 'wickets': 7.0},
 'DJ Willey': {'balls': 221, 'wickets': 7.0},
 'B Stanlake': {'balls': 150, 'wickets': 7.0},
 'OF Smith': {'balls': 95, 'wickets': 7.0},
 'FH Edwards': {'balls': 150, 'wickets': 6.0},
 'V Sehwag': {'balls': 138, 'wickets': 6.0},
 'KMDN Kulasekara': {'balls': 107, 'wickets': 6.0},
 'Ramandeep Singh': {'balls': 45, 'wickets': 6.0},
 'AS Roy': {'balls': 142, 'wickets': 6.0},
 'RV Gomez': {'balls': 97, 'wickets': 6.0},
 'JE Taylor': {'balls': 122, 'wickets': 6.0},
 'S Narwal': {'balls': 113, 'wickets': 6.0},
 'R Shepherd': {'balls': 133, 'wickets': 6.0},
 'S Dube': {'balls': 117, 'wickets': 6.0},
 'S Kaushik': {'balls': 210, 'wickets': 6.0},
 'VS Malik': {'balls': 212, 'wickets': 6.0},
 'Fazalhaq Farooqi': {'balls': 162, 'wickets': 6.0},
 'Jaskaran Singh': {'balls': 111, 'wickets': 6.0},
 'M de Lange': {'balls': 116, 'wickets': 6.0},
 'DG Nalkande': {'balls': 89, 'wickets': 6.0},
 'S Tyagi': {'balls': 220, 'wickets': 6.0},
 'MG Bracewell': {'balls': 66, 'wickets': 6.0},
 'SB Bangar': {'balls': 153, 'wickets': 6.0},
 'Arshad Khan': {'balls': 153, 'wickets': 6.0},
 'SS Cottrell': {'balls': 131, 'wickets': 6.0},
 'R Sathish': {'balls': 144, 'wickets': 6.0},
 'A Choudhary': {'balls': 108, 'wickets': 5.0},
 'RJW Topley': {'balls': 107, 'wickets': 5.0},
 'V Kohli': {'balls': 264, 'wickets': 5.0},
 'TM Dilshan': {'balls': 275, 'wickets': 5.0},
 'Shoaib Akhtar': {'balls': 46, 'wickets': 5.0},
 'Shoaib Ahmed': {'balls': 103, 'wickets': 5.0},
 'SB Wagh': {'balls': 108, 'wickets': 5.0},
 'S Ladda': {'balls': 141, 'wickets': 5.0},
 'O Thomas': {'balls': 63, 'wickets': 5.0},
 'PD Collingwood': {'balls': 90, 'wickets': 5.0},
 'R Parag': {'balls': 181, 'wickets': 5.0},
 'AP Dole': {'balls': 73, 'wickets': 5.0},
 'KL Nagarkoti': {'balls': 185, 'wickets': 5.0},
 'Gurkeerat Singh': {'balls': 82, 'wickets': 5.0},
 'HR Shokeen': {'balls': 213, 'wickets': 5.0},
 'K Khejroliya': {'balls': 129, 'wickets': 5.0},
 'L Ablish': {'balls': 45, 'wickets': 5.0},
 'Akash Singh': {'balls': 141, 'wickets': 5.0},
 'S Dhawan': {'balls': 49, 'wickets': 4.0},
 'DJ Muthuswami': {'balls': 84, 'wickets': 4.0},
 'Nithish Kumar Reddy': {'balls': 118, 'wickets': 4.0},
 'WA Mota': {'balls': 75, 'wickets': 4.0},
 'SH Johnson': {'balls': 99, 'wickets': 4.0},
 'Ankit Soni': {'balls': 112, 'wickets': 4.0},
 'LE Plunkett': {'balls': 154, 'wickets': 4.0},
 'D du Preez': {'balls': 43, 'wickets': 4.0},
 'Arjun Tendulkar': {'balls': 83, 'wickets': 4.0},
 'Parvez Rasool': {'balls': 200, 'wickets': 4.0},
 'DP Vijaykumar': {'balls': 159, 'wickets': 4.0},
 'Shivam Sharma': {'balls': 114, 'wickets': 4.0},
 'Y Nagar': {'balls': 72, 'wickets': 4.0},
 'Yudhvir Singh': {'balls': 74, 'wickets': 4.0},
 'Azmatullah Omarzai': {'balls': 131, 'wickets': 4.0},
 'T Stubbs': {'balls': 25, 'wickets': 4.0},
 'GHS Garton': {'balls': 97, 'wickets': 3.0},
 'T Shamsi': {'balls': 120, 'wickets': 3.0},
 'JA Richardson': {'balls': 94, 'wickets': 3.0},
 'SM Harwood': {'balls': 67, 'wickets': 3.0},
 'DAJ Bracewell': {'balls': 25, 'wickets': 3.0},
 'Sikandar Raza': {'balls': 88, 'wickets': 3.0},
 'A Uniyal': {'balls': 38, 'wickets': 3.0},
 'MJ Clarke': {'balls': 66, 'wickets': 3.0},
 'TM Head': {'balls': 58, 'wickets': 3.0},
 'DJ Thornely': {'balls': 44, 'wickets': 3.0},
 'MJ Henry': {'balls': 105, 'wickets': 3.0},
 'SM Boland': {'balls': 43, 'wickets': 3.0},
 'Gagandeep Singh': {'balls': 84, 'wickets': 3.0},
 'AL Menaria': {'balls': 113, 'wickets': 3.0},
 'RS Hangargekar': {'balls': 43, 'wickets': 3.0},
 'VR Iyer': {'balls': 84, 'wickets': 3.0},
 'Sachin Baby': {'balls': 10, 'wickets': 3.0},
 'RJ Peterson': {'balls': 48, 'wickets': 3.0},
 'JM Kemp': {'balls': 47, 'wickets': 3.0},
 'P Sahu': {'balls': 107, 'wickets': 3.0},
 'K Santokie': {'balls': 51, 'wickets': 3.0},
 'RN ten Doeschate': {'balls': 83, 'wickets': 3.0},
 'JJ van der Wath': {'balls': 76, 'wickets': 3.0},
 'R Ninan': {'balls': 36, 'wickets': 3.0},
 'JW Hastings': {'balls': 61, 'wickets': 3.0},
 'JPR Scantlebury-Searles': {'balls': 45, 'wickets': 2.0},
 'MA Khote': {'balls': 30, 'wickets': 2.0},
 'Shoaib Malik': {'balls': 58, 'wickets': 2.0},
 'A Badoni': {'balls': 25, 'wickets': 2.0},
 'V Kaverappa': {'balls': 24, 'wickets': 2.0},
 'A Flintoff': {'balls': 66, 'wickets': 2.0},
 'D Kalyankrishna': {'balls': 50, 'wickets': 2.0},
 'A Kamboj': {'balls': 68, 'wickets': 2.0},
 'LJ Wright': {'balls': 75, 'wickets': 2.0},
 'WG Jacks': {'balls': 55, 'wickets': 2.0},
 'K Yadav': {'balls': 54, 'wickets': 2.0},
 'KA Maharaj': {'balls': 36, 'wickets': 2.0},
 'C Nanda': {'balls': 50, 'wickets': 2.0},
 'KJ Abbott': {'balls': 102, 'wickets': 2.0},
 'FA Allen': {'balls': 91, 'wickets': 2.0},
 'MK Lomror': {'balls': 94, 'wickets': 2.0},
 'B Geeves': {'balls': 49, 'wickets': 2.0},
 'PH Solanki': {'balls': 36, 'wickets': 2.0},
 'Abdul Samad': {'balls': 55, 'wickets': 2.0},
 'GD Phillips': {'balls': 31, 'wickets': 2.0},
 'SC Kuggeleijn': {'balls': 50, 'wickets': 2.0},
 'SD Chitnis': {'balls': 38, 'wickets': 2.0},
 'DNT Zoysa': {'balls': 69, 'wickets': 2.0},
 'Mohammad Hafeez': {'balls': 63, 'wickets': 2.0},
 'P Suyal': {'balls': 107, 'wickets': 2.0},
 'Mayank Dagar': {'balls': 138, 'wickets': 2.0},
 'AK Markram': {'balls': 123, 'wickets': 2.0},
 'ND Doshi': {'balls': 57, 'wickets': 2.0},
 'AU Rashid': {'balls': 60, 'wickets': 2.0},
 'Y Prithvi Raj': {'balls': 33, 'wickets': 1.0},
 'S Vidyut': {'balls': 13, 'wickets': 1.0},
 'IC Porel': {'balls': 26, 'wickets': 1.0},
 'RJ Gleeson': {'balls': 51, 'wickets': 1.0},
 'KT Maphaka': {'balls': 39, 'wickets': 1.0},
 'SA Abbott': {'balls': 59, 'wickets': 1.0},
 'V Viyaskanth': {'balls': 60, 'wickets': 1.0},
 'GS Sandhu': {'balls': 48, 'wickets': 1.0},
 'DJM Short': {'balls': 18, 'wickets': 1.0},
 'CJ McKay': {'balls': 42, 'wickets': 1.0},
 'A Nel': {'balls': 18, 'wickets': 1.0},
 'AM Rahane': {'balls': 6, 'wickets': 1.0},
 'D Jansen': {'balls': 28, 'wickets': 1.0},
 'CL White': {'balls': 46, 'wickets': 1.0},

In [63]:
top_players('batter')

{'J Fraser-McGurk': {'runs': 330, 'balls': 150, 'strike_rate': 220.0},
 'Shahid Afridi': {'runs': 81, 'balls': 46, 'strike_rate': 176.09},
 'WG Jacks': {'runs': 230, 'balls': 133, 'strike_rate': 172.93},
 'PD Salt': {'runs': 653, 'balls': 385, 'strike_rate': 169.61},
 'T Stubbs': {'runs': 405, 'balls': 239, 'strike_rate': 169.46},
 'R Shepherd': {'runs': 115, 'balls': 68, 'strike_rate': 169.12},
 'TM Head': {'runs': 772, 'balls': 458, 'strike_rate': 168.56},
 'LJ Wright': {'runs': 106, 'balls': 63, 'strike_rate': 168.25},
 'Naman Dhir': {'runs': 140, 'balls': 84, 'strike_rate': 166.67},
 'KK Cooper': {'runs': 116, 'balls': 70, 'strike_rate': 165.71},
 'AD Russell': {'runs': 2488, 'balls': 1515, 'strike_rate': 164.22},
 'Kamran Akmal': {'runs': 128, 'balls': 78, 'strike_rate': 164.1},
 'Avesh Khan': {'runs': 41, 'balls': 25, 'strike_rate': 164.0},
 'BCJ Cutting': {'runs': 238, 'balls': 146, 'strike_rate': 163.01},
 'H Klaasen': {'runs': 993, 'balls': 613, 'strike_rate': 161.99},
 'Ramandeep Singh': {'runs': 170, 'balls': 106, 'strike_rate': 160.38},
 'Ashutosh Sharma': {'runs': 189, 'balls': 118, 'strike_rate': 160.17},
 'TH David': {'runs': 659, 'balls': 417, 'strike_rate': 158.03},
 'D Pretorius': {'runs': 44, 'balls': 28, 'strike_rate': 157.14},
 'SB Dubey': {'runs': 33, 'balls': 21, 'strike_rate': 157.14},
 'SP Narine': {'runs': 1534, 'balls': 984, 'strike_rate': 155.89},
 'Shashank Singh': {'runs': 423, 'balls': 272, 'strike_rate': 155.51},
 'K Gowtham': {'runs': 247, 'balls': 159, 'strike_rate': 155.35},
 'N Pooran': {'runs': 1769, 'balls': 1143, 'strike_rate': 154.77},
 'LS Livingstone': {'runs': 939, 'balls': 609, 'strike_rate': 154.19},
 'Rashid Khan': {'runs': 545, 'balls': 355, 'strike_rate': 153.52},
 'R Ravindra': {'runs': 222, 'balls': 146, 'strike_rate': 152.05},
 'CR Brathwaite': {'runs': 181, 'balls': 120, 'strike_rate': 150.83},
 'Bipul Sharma': {'runs': 187, 'balls': 124, 'strike_rate': 150.81},
 'JC Archer': {'runs': 199, 'balls': 132, 'strike_rate': 150.76},
 'GJ Maxwell': {'runs': 2772, 'balls': 1842, 'strike_rate': 150.49},
 'AUK Pathan': {'runs': 39, 'balls': 26, 'strike_rate': 150.0},
 'C Green': {'runs': 707, 'balls': 472, 'strike_rate': 149.79},
 'CH Morris': {'runs': 618, 'balls': 413, 'strike_rate': 149.64},
 'RM Patidar': {'runs': 799, 'balls': 534, 'strike_rate': 149.63},
 'A Raghuvanshi': {'runs': 163, 'balls': 109, 'strike_rate': 149.54},
 'Abhishek Sharma': {'runs': 1377, 'balls': 925, 'strike_rate': 148.86},
 'V Sehwag': {'runs': 2728, 'balls': 1833, 'strike_rate': 148.83},
 'AB de Villiers': {'runs': 5181, 'balls': 3487, 'strike_rate': 148.58},
 'LPC Silva': {'runs': 40, 'balls': 27, 'strike_rate': 148.15},
 'AP Dole': {'runs': 34, 'balls': 23, 'strike_rate': 147.83},
 'Abishek Porel': {'runs': 360, 'balls': 244, 'strike_rate': 147.54},
 'RR Rossouw': {'runs': 473, 'balls': 321, 'strike_rate': 147.35},
 'YBK Jaiswal': {'runs': 1607, 'balls': 1095, 'strike_rate': 146.76},
 'Dhruv Jurel': {'runs': 347, 'balls': 237, 'strike_rate': 146.41},
 'SD Hope': {'runs': 183, 'balls': 125, 'strike_rate': 146.4},
 'JM Sharma': {'runs': 730, 'balls': 501, 'strike_rate': 145.71},
 'SO Hetmyer': {'runs': 1243, 'balls': 854, 'strike_rate': 145.55},
 'RR Pant': {'runs': 3297, 'balls': 2296, 'strike_rate': 143.6},
 'PJ Cummins': {'runs': 515, 'balls': 359, 'strike_rate': 143.45},
 'Arshad Khan': {'runs': 96, 'balls': 67, 'strike_rate': 143.28},
 'PP Shaw': {'runs': 1892, 'balls': 1321, 'strike_rate': 143.22},
 'P Simran Singh': {'runs': 756, 'balls': 528, 'strike_rate': 143.18},
 'A Ashish Reddy': {'runs': 280, 'balls': 196, 'strike_rate': 142.86},
 'MF Maharoof': {'runs': 177, 'balls': 124, 'strike_rate': 142.74},
 'Misbah-ul-Haq': {'runs': 117, 'balls': 82, 'strike_rate': 142.68},
 'SA Yadav': {'runs': 3594, 'balls': 2522, 'strike_rate': 142.51},
 'JC Buttler': {'runs': 3583, 'balls': 2519, 'strike_rate': 142.24},
 'CH Gayle': {'runs': 4997, 'balls': 3516, 'strike_rate': 142.12},
 'Abdul Samad': {'runs': 579, 'balls': 408, 'strike_rate': 141.91},
 'R Powell': {'runs': 360, 'balls': 254, 'strike_rate': 141.73},
 'LH Ferguson': {'runs': 68, 'balls': 48, 'strike_rate': 141.67},
 'D Wiese': {'runs': 148, 'balls': 105, 'strike_rate': 140.95},
 'Vivrant Sharma': {'runs': 69, 'balls': 49, 'strike_rate': 140.82},
 'Mohammad Nabi': {'runs': 221, 'balls': 157, 'strike_rate': 140.76},
 'KA Pollard': {'runs': 3437, 'balls': 2447, 'strike_rate': 140.46},
 'MJ Lumb': {'runs': 278, 'balls': 198, 'strike_rate': 140.4},
 'JM Bairstow': {'runs': 1589, 'balls': 1132, 'strike_rate': 140.37},
 'HH Pandya': {'runs': 2534, 'balls': 1814, 'strike_rate': 139.69},
 'Atharva Taide': {'runs': 247, 'balls': 177, 'strike_rate': 139.55},
 'S Dube': {'runs': 1502, 'balls': 1077, 'strike_rate': 139.46},
 'Tilak Varma': {'runs': 1156, 'balls': 830, 'strike_rate': 139.28},
 'Sunny Singh': {'runs': 43, 'balls': 31, 'strike_rate': 138.71},
 'DP Conway': {'runs': 924, 'balls': 669, 'strike_rate': 138.12},
 'YK Pathan': {'runs': 3222, 'balls': 2334, 'strike_rate': 138.05},
 'HM Amla': {'runs': 577, 'balls': 418, 'strike_rate': 138.04},
 'PBB Rajapaksa': {'runs': 277, 'balls': 201, 'strike_rate': 137.81},
 'MJ Guptill': {'runs': 271, 'balls': 197, 'strike_rate': 137.56},
 'D Salunkhe': {'runs': 33, 'balls': 24, 'strike_rate': 137.5},
 'KR Mayers': {'runs': 379, 'balls': 276, 'strike_rate': 137.32},
 'Nithish Kumar Reddy': {'runs': 303, 'balls': 221, 'strike_rate': 137.1},
 'RN ten Doeschate': {'runs': 326, 'balls': 238, 'strike_rate': 136.97},
 'JA Morkel': {'runs': 975, 'balls': 712, 'strike_rate': 136.94},
 'MM Ali': {'runs': 1162, 'balls': 849, 'strike_rate': 136.87},
 'MP Stoinis': {'runs': 1866, 'balls': 1366, 'strike_rate': 136.6},
 'RK Singh': {'runs': 893, 'balls': 654, 'strike_rate': 136.54},
 'CA Lynn': {'runs': 1329, 'balls': 974, 'strike_rate': 136.45},
 'RA Tripathi': {'runs': 2236, 'balls': 1650, 'strike_rate': 135.52},
 'M Morkel': {'runs': 126, 'balls': 93, 'strike_rate': 135.48},
 'MK Lomror': {'runs': 527, 'balls': 389, 'strike_rate': 135.48},
 'DA Warner': {'runs': 6567, 'balls': 4849, 'strike_rate': 135.43},
 'SV Samson': {'runs': 4419, 'balls': 3270, 'strike_rate': 135.14},
 'DA Miller': {'runs': 2924, 'balls': 2171, 'strike_rate': 134.68},
 'SN Thakur': {'runs': 307, 'balls': 228, 'strike_rate': 134.65},
 'PVD Chameera': {'runs': 43, 'balls': 32, 'strike_rate': 134.38},
 'B Sai Sudharsan': {'runs': 1034, 'balls': 770, 'strike_rate': 134.29},
 'SR Watson': {'runs': 3880, 'balls': 2892, 'strike_rate': 134.16},
 'N Wadhera': {'runs': 350, 'balls': 261, 'strike_rate': 134.1},
 'ST Jayasuriya': {'runs': 768, 'balls': 573, 'strike_rate': 134.03},
 'M Shahrukh Khan': {'runs': 553, 'balls': 413, 'strike_rate': 133.9},
 'RD Gaikwad': {'runs': 2380, 'balls': 1781, 'strike_rate': 133.63},
 'JJ Roy': {'runs': 614, 'balls': 460, 'strike_rate': 133.48},
 'AN Ahmed': {'runs': 36, 'balls': 27, 'strike_rate': 133.33},
 'B Akhil': {'runs': 76, 'balls': 57, 'strike_rate': 133.33},
 'F du Plessis': {'runs': 4571, 'balls': 3435, 'strike_rate': 133.07},
 'AC Gilchrist': {'runs': 2069, 'balls': 1555, 'strike_rate': 133.05},
 'MS Dhoni': {'runs': 5243, 'balls': 3947, 'strike_rate': 132.84},
 'Ishan Kishan': {'runs': 2644, 'balls': 1991, 'strike_rate': 132.8},
 'JR Hopes': {'runs': 417, 'balls': 314, 'strike_rate': 132.8},
 'VR Iyer': {'runs': 1326, 'balls': 1000, 'strike_rate': 132.6},
 'SK Raina': {'runs': 5536, 'balls': 4177, 'strike_rate': 132.54},
 'C de Grandhomme': {'runs': 303, 'balls': 229, 'strike_rate': 132.31},
 'DR Smith': {'runs': 2385, 'balls': 1803, 'strike_rate': 132.28},
 'Shubman Gill': {'runs': 3216, 'balls': 2432, 'strike_rate': 132.24},
 'BJ Rohrer': {'runs': 193, 'balls': 146, 'strike_rate': 132.19},
 'KP Pietersen': {'runs': 1001, 'balls': 758, 'strike_rate': 132.06},
 'ML Hayden': {'runs': 1107, 'balls': 839, 'strike_rate': 131.94},
 'AC Blizzard': {'runs': 120, 'balls': 91, 'strike_rate': 131.87},
 'KD Karthik': {'runs': 4843, 'balls': 3687, 'strike_rate': 131.35},
 'SM Curran': {'runs': 883, 'balls': 673, 'strike_rate': 131.2},
 'DL Chahar': {'runs': 80, 'balls': 61, 'strike_rate': 131.15},
 'Q de Kock': {'runs': 3160, 'balls': 2410, 'strike_rate': 131.12},
 'E Lewis': {'runs': 654, 'balls': 499, 'strike_rate': 131.06},
 'KL Rahul': {'runs': 4689, 'balls': 3578, 'strike_rate': 131.05},
 'Harbhajan Singh': {'runs': 833, 'balls': 636, 'strike_rate': 130.97},
 'N Rana': {'runs': 2636, 'balls': 2015, 'strike_rate': 130.82},
 'A Mithun': {'runs': 34, 'balls': 26, 'strike_rate': 130.77},
 'D Brevis': {'runs': 230, 'balls': 176, 'strike_rate': 130.68},
 'MS Gony': {'runs': 99, 'balls': 76, 'strike_rate': 130.26},
 'BA Stokes': {'runs': 935, 'balls': 718, 'strike_rate': 130.22},
 'SE Marsh': {'runs': 2489, 'balls': 1913, 'strike_rate': 130.11},
 'NLTC Perera': {'runs': 424, 'balls': 326, 'strike_rate': 130.06},
 'JP Faulkner': {'runs': 527, 'balls': 406, 'strike_rate': 129.8},
 'JD Ryder': {'runs': 604, 'balls': 466, 'strike_rate': 129.61},
 'PN Mankad': {'runs': 97, 'balls': 75, 'strike_rate': 129.33},
 'R Parag': {'runs': 1173, 'balls': 909, 'strike_rate': 129.04},
 'R Tewatia': {'runs': 1013, 'balls': 788, 'strike_rate': 128.55},
 'V Kohli': {'runs': 8014, 'balls': 6236, 'strike_rate': 128.51},
 'SN Khan': {'runs': 585, 'balls': 456, 'strike_rate': 128.29},
 'MA Agarwal': {'runs': 2669, 'balls': 2081, 'strike_rate': 128.26},
 'DJ Mitchell': {'runs': 351, 'balls': 274, 'strike_rate': 128.1},
 'KH Pandya': {'runs': 1647, 'balls': 1287, 'strike_rate': 127.97},
 'RG Sharma': {'runs': 6630, 'balls': 5183, 'strike_rate': 127.92},
 'PD Collingwood': {'runs': 203, 'balls': 159, 'strike_rate': 127.67},
 'A Manohar': {'runs': 231, 'balls': 181, 'strike_rate': 127.62},
 'S Narwal': {'runs': 37, 'balls': 29, 'strike_rate': 127.59},
 'Sikandar Raza': {'runs': 182, 'balls': 143, 'strike_rate': 127.27},
 'TR Birt': {'runs': 75, 'balls': 59, 'strike_rate': 127.12},
 'BB McCullum': {'runs': 2882, 'balls': 2272, 'strike_rate': 126.85},
 'Rahmanullah Gurbaz': {'runs': 289, 'balls': 228, 'strike_rate': 126.75},
 'SM Pollock': {'runs': 147, 'balls': 116, 'strike_rate': 126.72},
 'AC Voges': {'runs': 181, 'balls': 143, 'strike_rate': 126.57},
 'AK Markram': {'runs': 995, 'balls': 787, 'strike_rate': 126.43},
 'SM Katich': {'runs': 241, 'balls': 191, 'strike_rate': 126.18},
 'RV Uthappa': {'runs': 4954, 'balls': 3927, 'strike_rate': 126.15},
 'Ankit Sharma': {'runs': 87, 'balls': 69, 'strike_rate': 126.09},
 'S Vidyut': {'runs': 145, 'balls': 115, 'strike_rate': 126.09},
 'SW Billings': {'runs': 503, 'balls': 399, 'strike_rate': 126.07},
 'STR Binny': {'runs': 880, 'balls': 700, 'strike_rate': 125.71},
 'A Badoni': {'runs': 634, 'balls': 505, 'strike_rate': 125.54},
 'KK Nair': {'runs': 1496, 'balls': 1192, 'strike_rate': 125.5},
 'M Vohra': {'runs': 1083, 'balls': 863, 'strike_rate': 125.49},
 'CL White': {'runs': 971, 'balls': 774, 'strike_rate': 125.45},
 'AR Patel': {'runs': 1653, 'balls': 1318, 'strike_rate': 125.42},
 'DJ Hooda': {'runs': 1466, 'balls': 1170, 'strike_rate': 125.3},
 'V Shankar': {'runs': 1115, 'balls': 890, 'strike_rate': 125.28},
 'DJ Bravo': {'runs': 1560, 'balls': 1247, 'strike_rate': 125.1},
 'MR Marsh': {'runs': 665, 'balls': 532, 'strike_rate': 125.0},
 'OA Shah': {'runs': 506, 'balls': 405, 'strike_rate': 124.94},
 'MC Henriques': {'runs': 1000, 'balls': 801, 'strike_rate': 124.84},
 'SPD Smith': {'runs': 2495, 'balls': 1999, 'strike_rate': 124.81},
 'Yuvraj Singh': {'runs': 2754, 'balls': 2207, 'strike_rate': 124.78},
 'Azhar Mahmood': {'runs': 388, 'balls': 311, 'strike_rate': 124.76},
 'A Symonds': {'runs': 974, 'balls': 781, 'strike_rate': 124.71},
 'AT Rayudu': {'runs': 4348, 'balls': 3490, 'strike_rate': 124.58},
 'RA Jadeja': {'runs': 2959, 'balls': 2378, 'strike_rate': 124.43},
 'AD Hales': {'runs': 148, 'balls': 119, 'strike_rate': 124.37},
 'WP Saha': {'runs': 2934, 'balls': 2368, 'strike_rate': 123.9},
 'MV Boucher': {'runs': 394, 'balls': 318, 'strike_rate': 123.9},
 'MN van Wyk': {'runs': 167, 'balls': 135, 'strike_rate': 123.7},
 'Azmatullah Omarzai': {'runs': 42, 'balls': 34, 'strike_rate': 123.53},
 'S Dhawan': {'runs': 6769, 'balls': 5483, 'strike_rate': 123.45},
 'CJ Anderson': {'runs': 538, 'balls': 436, 'strike_rate': 123.39},
 'AJ Finch': {'runs': 2092, 'balls': 1696, 'strike_rate': 123.35},
 'SS Iyer': {'runs': 3131, 'balls': 2545, 'strike_rate': 123.03},
 'KS Williamson': {'runs': 2132, 'balls': 1734, 'strike_rate': 122.95},
 'C Munro': {'runs': 177, 'balls': 144, 'strike_rate': 122.92},
 'LMP Simmons': {'runs': 1079, 'balls': 878, 'strike_rate': 122.89},
 'AS Yadav': {'runs': 49, 'balls': 40, 'strike_rate': 122.5},
 'B Lee': {'runs': 124, 'balls': 102, 'strike_rate': 121.57},
 'BJ Hodge': {'runs': 1400, 'balls': 1153, 'strike_rate': 121.42},
 'P Negi': {'runs': 365, 'balls': 301, 'strike_rate': 121.26},
 'UT Khawaja': {'runs': 127, 'balls': 105, 'strike_rate': 120.95},
 'AD Mathews': {'runs': 724, 'balls': 599, 'strike_rate': 120.87},
 'JP Duminy': {'runs': 2029, 'balls': 1680, 'strike_rate': 120.77},
 'AM Rahane': {'runs': 4642, 'balls': 3858, 'strike_rate': 120.32},
 'LA Pomersbach': {'runs': 302, 'balls': 251, 'strike_rate': 120.32},
 'Mandeep Singh': {'runs': 1706, 'balls': 1418, 'strike_rate': 120.31},
 'SA Asnodkar': {'runs': 423, 'balls': 352, 'strike_rate': 120.17},
 'GJ Bailey': {'runs': 663, 'balls': 552, 'strike_rate': 120.11},
 'DJ Hussey': {'runs': 1322, 'balls': 1101, 'strike_rate': 120.07},
 'LRPL Taylor': {'runs': 1017, 'balls': 847, 'strike_rate': 120.07},
 'Joginder Sharma': {'runs': 36, 'balls': 30, 'strike_rate': 120.0},
 'MEK Hussey': {'runs': 1977, 'balls': 1648, 'strike_rate': 119.96},
 'DH Yagnik': {'runs': 170, 'balls': 142, 'strike_rate': 119.72},
 'G Gambhir': {'runs': 4217, 'balls': 3524, 'strike_rate': 119.67},
 'Shakib Al Hasan': {'runs': 795, 'balls': 665, 'strike_rate': 119.55},
 'HC Brook': {'runs': 190, 'balls': 159, 'strike_rate': 119.5},
 'AB McDonald': {'runs': 123, 'balls': 103, 'strike_rate': 119.42},
 'KM Jadhav': {'runs': 1208, 'balls': 1012, 'strike_rate': 119.37},
 'JO Holder': {'runs': 259, 'balls': 217, 'strike_rate': 119.35},
 'T Taibu': {'runs': 31, 'balls': 26, 'strike_rate': 119.23},
 'EJG Morgan': {'runs': 1406, 'balls': 1181, 'strike_rate': 119.05},
 'AP Tare': {'runs': 339, 'balls': 285, 'strike_rate': 118.95},
 'Anmolpreet Singh': {'runs': 139, 'balls': 117, 'strike_rate': 118.8},
 'DPMD Jayawardene': {'runs': 1808, 'balls': 1522, 'strike_rate': 118.79},
 'M Vijay': {'runs': 2619, 'balls': 2208, 'strike_rate': 118.61},
 'Sameer Rizvi': {'runs': 51, 'balls': 43, 'strike_rate': 118.6},
 'KC Sangakkara': {'runs': 1687, 'balls': 1424, 'strike_rate': 118.47},
 'KS Bharat': {'runs': 199, 'balls': 168, 'strike_rate': 118.45},
 'MG Bracewell': {'runs': 58, 'balls': 49, 'strike_rate': 118.37},
 'S Sohal': {'runs': 368, 'balls': 311, 'strike_rate': 118.33},
 'GD Phillips': {'runs': 65, 'balls': 55, 'strike_rate': 118.18},
 'KA Jamieson': {'runs': 65, 'balls': 55, 'strike_rate': 118.18},
 'MW Short': {'runs': 117, 'balls': 99, 'strike_rate': 118.18},
 'R Bhatia': {'runs': 342, 'balls': 290, 'strike_rate': 117.93},
 'D Padikkal': {'runs': 1559, 'balls': 1323, 'strike_rate': 117.84},
 'TK Curran': {'runs': 127, 'balls': 108, 'strike_rate': 117.59},
 'DJG Sammy': {'runs': 295, 'balls': 251, 'strike_rate': 117.53},
 'MK Pandey': {'runs': 3859, 'balls': 3288, 'strike_rate': 117.37},
 'Gurkeerat Singh': {'runs': 511, 'balls': 436, 'strike_rate': 117.2},
 'Sachin Baby': {'runs': 144, 'balls': 123, 'strike_rate': 117.07},
 'PC Valthaty': {'runs': 505, 'balls': 432, 'strike_rate': 116.9},
 'IK Pathan': {'runs': 1150, 'balls': 985, 'strike_rate': 116.75},
 'PA Patel': {'runs': 2848, 'balls': 2442, 'strike_rate': 116.63},
 'MJ McClenaghan': {'runs': 85, 'balls': 73, 'strike_rate': 116.44},
 'HV Patel': {'runs': 249, 'balls': 214, 'strike_rate': 116.36},
 'Sohail Tanvir': {'runs': 36, 'balls': 31, 'strike_rate': 116.13},
 'Harpreet Brar': {'runs': 233, 'balls': 201, 'strike_rate': 115.92},
 'JD Unadkat': {'runs': 197, 'balls': 170, 'strike_rate': 115.88},
 'S Badrinath': {'runs': 1441, 'balls': 1245, 'strike_rate': 115.74},
 'SS Tiwary': {'runs': 1494, 'balls': 1291, 'strike_rate': 115.72},
 'DB Ravi Teja': {'runs': 375, 'balls': 325, 'strike_rate': 115.38},
 'Anuj Rawat': {'runs': 318, 'balls': 276, 'strike_rate': 115.22},
 'AJ Tye': {'runs': 91, 'balls': 79, 'strike_rate': 115.19},
 'TL Suman': {'runs': 676, 'balls': 587, 'strike_rate': 115.16},
 'Shahbaz Ahmed': {'runs': 536, 'balls': 467, 'strike_rate': 114.78},
 'KV Sharma': {'runs': 351, 'balls': 306, 'strike_rate': 114.71},
 'SP Fleming': {'runs': 196, 'balls': 171, 'strike_rate': 114.62},
 'R Ashwin': {'runs': 800, 'balls': 698, 'strike_rate': 114.61},
 'R Sathish': {'runs': 270, 'balls': 236, 'strike_rate': 114.41},
 'KC Cariappa': {'runs': 24, 'balls': 21, 'strike_rate': 114.29},
 'AM Nayar': {'runs': 672, 'balls': 588, 'strike_rate': 114.29},
 'NV Ojha': {'runs': 1554, 'balls': 1360, 'strike_rate': 114.26},
 'SR Tendulkar': {'runs': 2334, 'balls': 2044, 'strike_rate': 114.19},
 'LA Carseldine': {'runs': 81, 'balls': 71, 'strike_rate': 114.08},
 'Y Venugopal Rao': {'runs': 985, 'balls': 865, 'strike_rate': 113.87},
 'DB Das': {'runs': 304, 'balls': 267, 'strike_rate': 113.86},
 'MK Tiwary': {'runs': 1695, 'balls': 1489, 'strike_rate': 113.83},
 'Sanvir Singh': {'runs': 25, 'balls': 22, 'strike_rate': 113.64},
 'RS Bopara': {'runs': 531, 'balls': 468, 'strike_rate': 113.46},
 'R Dravid': {'runs': 2174, 'balls': 1918, 'strike_rate': 113.35},
 'LR Shukla': {'runs': 405, 'balls': 358, 'strike_rate': 113.13},
 'NL McCullum': {'runs': 26, 'balls': 23, 'strike_rate': 113.04},
 'AP Majumdar': {'runs': 87, 'balls': 77, 'strike_rate': 112.99},
 'J Suchith': {'runs': 70, 'balls': 62, 'strike_rate': 112.9},
 'AS Raut': {'runs': 194, 'balls': 172, 'strike_rate': 112.79},
 'DJM Short': {'runs': 115, 'balls': 102, 'strike_rate': 112.75},
 'DT Christian': {'runs': 460, 'balls': 408, 'strike_rate': 112.75},
 'S Anirudha': {'runs': 136, 'balls': 121, 'strike_rate': 112.4},
 'J Botha': {'runs': 409, 'balls': 364, 'strike_rate': 112.36},
 'Salman Butt': {'runs': 193, 'balls': 172, 'strike_rate': 112.21},
 'RE Levi': {'runs': 83, 'balls': 74, 'strike_rate': 112.16},
 'CA Ingram': {'runs': 205, 'balls': 183, 'strike_rate': 112.02},
 'AB Agarkar': {'runs': 179, 'balls': 160, 'strike_rate': 111.87},
 'R Dhawan': {'runs': 210, 'balls': 188, 'strike_rate': 111.7},
 'VH Zol': {'runs': 29, 'balls': 26, 'strike_rate': 111.54},
 'SS Prabhudessai': {'runs': 126, 'balls': 113, 'strike_rate': 111.5},
 'MD Mishra': {'runs': 237, 'balls': 213, 'strike_rate': 111.27},
 'BR Dunk': {'runs': 40, 'balls': 36, 'strike_rate': 111.11},
 'TG Southee': {'runs': 120, 'balls': 108, 'strike_rate': 111.11},
 'S Rana': {'runs': 91, 'balls': 82, 'strike_rate': 110.98},
 'WPUJC Vaas': {'runs': 81, 'balls': 73, 'strike_rate': 110.96},
 'Swapnil Singh': {'runs': 51, 'balls': 46, 'strike_rate': 110.87},
 'Washington Sundar': {'runs': 378, 'balls': 341, 'strike_rate': 110.85},
 'PK Garg': {'runs': 273, 'balls': 247, 'strike_rate': 110.53},
 'RE van der Merwe': {'runs': 159, 'balls': 144, 'strike_rate': 110.42},
 'AT Carey': {'runs': 32, 'balls': 29, 'strike_rate': 110.34},
 'TM Dilshan': {'runs': 1153, 'balls': 1047, 'strike_rate': 110.12},
 'B Chipli': {'runs': 280, 'balls': 256, 'strike_rate': 109.38},
 'NM Coulter-Nile': {'runs': 82, 'balls': 75, 'strike_rate': 109.33},
 'AL Menaria': {'runs': 401, 'balls': 367, 'strike_rate': 109.26},
 'M Markande': {'runs': 48, 'balls': 44, 'strike_rate': 109.09},
 'MA Khote': {'runs': 24, 'balls': 22, 'strike_rate': 109.09},
 'A Flintoff': {'runs': 62, 'balls': 57, 'strike_rate': 108.77},
 'AS Roy': {'runs': 26, 'balls': 24, 'strike_rate': 108.33},
 'MS Bisla': {'runs': 798, 'balls': 737, 'strike_rate': 108.28},
 'DJ Harris': {'runs': 111, 'balls': 103, 'strike_rate': 107.77},

# D) Venue

## 1) Venue Statistics

- stats of matches played on a specific venue,average score, winning Rate by chasing or defending , wickets , teams played till now, which toss decisions teams prefer,seasons played

In [67]:
def venue_stat(venue):
    # Fetching data for the respective venue
    records = ipl2[ipl2['venue'] == venue][['match_id', 'season', 'city', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner']]
    if not records.empty:
        # Seasons held at the venue
        seasons_played = sorted(records['season'].unique())

        # city
        city=records['city'].unique()[0]
        
        # Teams that played at the venue
        teams_played = list(set(list(records['team1'].unique()) + list(records['team2'].unique())))

        # Most preferred toss decision
        prefered_toss_decision = records['toss_decision'].value_counts().idxmax()

        # Fetch statistics from the related dataset
        new_records = ipl1[ipl1['match_id'].isin(records['match_id'])]
        grouped_data = new_records.groupby(['match_id', 'inning'])
        avg_runs = round(grouped_data['batsman_runs'].sum().mean(), 2)
        wickets_taken = new_records[new_records['is_wicket'] == 1]['is_wicket'].count()

        # number of matches played
        num_matches=records.shape[0]

        
        # Chasing and defending rates
        inning1_runs = new_records[new_records['inning'] == 1].groupby('match_id')['batsman_runs'].sum()
        inning2_runs = new_records[new_records['inning'] == 2].groupby('match_id')['batsman_runs'].sum()
        margin = inning1_runs - inning2_runs
        chased_match = (margin < 0).sum()
        defended_match = (margin >= 0).sum()

        chasing_rate = round((chased_match / margin.shape[0]) * 100, 2)
        defending_rate = round((defended_match / margin.shape[0]) * 100, 2)
        
        # min and max score of venue
        min_score=min(inning1_runs.min(),inning2_runs.min())
        max_score=max(inning1_runs.max(),inning2_runs.max())
        
        # Creating output dictionary
        venue_stats = {
            'venue': f'{venue}, {city}',
            'seasons_held': seasons_played,
            'teams_played': sorted(teams_played),
            'prefered_toss_decision': prefered_toss_decision,
            'number_matches':num_matches,
            'avg_score': avg_runs,
            'min_score':min_score,
            'max_score':max_score,
            'num_wickets': wickets_taken,
            'chasing_rate': chasing_rate,
            'defending_rate': defending_rate
        }
        return venue_stats
    else:
        return {'error': 'This venue is not represented in our data'}

In [68]:
venue_stat('Eden Gardens')

{'venue': 'Eden Gardens, Kolkata',
 'seasons_held': [2008,
  2010,
  2011,
  2012,
  2013,
  2014,
  2015,
  2016,
  2017,
  2018,
  2019,
  2022,
  2023,
  2024],
 'teams_played': ['Chennai Super Kings',
  'Delhi Capitals',
  'Gujarat Titans',
  'Kochi Tuskers Kerala',
  'Kolkata Knight Riders',
  'Lucknow Super Giants',
  'Mumbai Indians',
  'Punjab Kings',
  'Rajasthan Royals',
  'Rising Pune Supergiant',
  'Royal Challengers Bangalore',
  'Sunrisers Hyderabad'],
 'prefered_toss_decision': 'field',
 'number_matches': 93,
 'avg_score': 151.52,
 'min_score': 42,
 'max_score': 256,
 'num_wickets': 1071,
 'chasing_rate': 35.48,
 'defending_rate': 64.52}

## 2) top venues

In [70]:
def top_venues():
    # Initialize a list to store venue statistics
    venue_stats = []

    for venue in ipl2['venue'].unique():
        # Extract records for the venue
        records = ipl2[ipl2['venue'] == venue][['match_id', 'toss_decision']]
        
        # Calculate matches played
        num_matches = records['match_id'].nunique()

        # Check if matches played are more than 10
        if num_matches > 10:
            # Fetch data from ipl1 for the venue
            venue_matches = ipl1[ipl1['match_id'].isin(records['match_id'])]
            grouped_data = venue_matches.groupby(['match_id', 'inning'])
            
            # Calculate total runs scored at the venue
            total_runs = grouped_data['batsman_runs'].sum().sum()
            
            # Count total wickets taken at the venue
            total_wickets = venue_matches[venue_matches['is_wicket'] == 1]['is_wicket'].count()
            
            # Apply remaining criteria
            if total_runs > 1000 and total_wickets > 20:
                # Calculate average runs per inning
                avg_runs = round(grouped_data['batsman_runs'].sum().mean(), 2)

                # Most preferred toss decision
                prefered_toss_decision = records['toss_decision'].value_counts().idxmax()
                
                # Append venue statistics
                venue_stats.append({
                    'venue': venue,
                    'num_matches': num_matches,
                    'total_runs': total_runs,
                    'total_wickets': total_wickets,
                    'avg_runs': avg_runs,
                    'prefered_toss_decision': prefered_toss_decision
                })

    # Convert to DataFrame for sorting
    venue_df = pd.DataFrame(venue_stats)

    # Sort by total_runs (descending) and total_wickets (descending)
    sorted_venues = venue_df.sort_values(by=['total_runs', 'total_wickets'], ascending=[False, False])
    
    #  Convert to a dictionary with venues as keys
    response = sorted_venues.set_index('venue').T.to_dict()
    return response

In [134]:
top_venues()

{'Wankhede Stadium': {'num_matches': 118,
  'total_runs': 36919,
  'total_wickets': 1422,
  'avg_runs': 155.12,
  'prefered_toss_decision': 'field'},
 'M Chinnaswamy Stadium': {'num_matches': 94,
  'total_runs': 29075,
  'total_wickets': 1101,
  'avg_runs': 153.84,
  'prefered_toss_decision': 'field'},
 'Eden Gardens': {'num_matches': 93,
  'total_runs': 28182,
  'total_wickets': 1071,
  'avg_runs': 151.52,
  'prefered_toss_decision': 'field'},
 'MA Chidambaram Stadium': {'num_matches': 85,
  'total_runs': 25295,
  'total_wickets': 1023,
  'avg_runs': 145.37,
  'prefered_toss_decision': 'bat'},
 'Rajiv Gandhi International Stadium': {'num_matches': 77,
  'total_runs': 23158,
  'total_wickets': 899,
  'avg_runs': 148.45,
  'prefered_toss_decision': 'field'},
 'Punjab Cricket Association IS Bindra Stadium': {'num_matches': 61,
  'total_runs': 18929,
  'total_wickets': 690,
  'avg_runs': 155.16,
  'prefered_toss_decision': 'field'},
 'Feroz Shah Kotla': {'num_matches': 60,
  'total_runs': 17499,
  'total_wickets': 697,
  'avg_runs': 147.05,
  'prefered_toss_decision': 'field'},
 'Sawai Mansingh Stadium': {'num_matches': 57,
  'total_runs': 16746,
  'total_wickets': 623,
  'avg_runs': 146.89,
  'prefered_toss_decision': 'field'},
 'Dubai International Cricket Stadium': {'num_matches': 46,
  'total_runs': 13753,
  'total_wickets': 545,
  'avg_runs': 140.34,
  'prefered_toss_decision': 'field'},
 'Dr DY Patil Sports Academy': {'num_matches': 37,
  'total_runs': 10689,
  'total_wickets': 470,
  'avg_runs': 144.45,
  'prefered_toss_decision': 'field'},
 'Maharashtra Cricket Association Stadium': {'num_matches': 35,
  'total_runs': 10600,
  'total_wickets': 434,
  'avg_runs': 151.43,
  'prefered_toss_decision': 'field'},
 'Arun Jaitley Stadium': {'num_matches': 30,
  'total_runs': 10159,
  'total_wickets': 364,
  'avg_runs': 163.85,
  'prefered_toss_decision': 'field'},
 'Brabourne Stadium': {'num_matches': 27,
  'total_runs': 8760,
  'total_wickets': 331,
  'avg_runs': 162.22,
  'prefered_toss_decision': 'field'},
 'Sheikh Zayed Stadium': {'num_matches': 29,
  'total_runs': 8467,
  'total_wickets': 329,
  'avg_runs': 136.56,
  'prefered_toss_decision': 'bat'},
 'Sharjah Cricket Stadium': {'num_matches': 28,
  'total_runs': 8159,
  'total_wickets': 322,
  'avg_runs': 145.7,
  'prefered_toss_decision': 'field'},
 'Narendra Modi Stadium': {'num_matches': 24,
  'total_runs': 7808,
  'total_wickets': 284,
  'avg_runs': 162.67,
  'prefered_toss_decision': 'field'},
 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium': {'num_matches': 15,
  'total_runs': 4323,
  'total_wickets': 191,
  'avg_runs': 144.1,
  'prefered_toss_decision': 'field'},
 'Subrata Roy Sahara Stadium': {'num_matches': 16,
  'total_runs': 4296,
  'total_wickets': 183,
  'avg_runs': 134.25,
  'prefered_toss_decision': 'bat'},
 'Himachal Pradesh Cricket Association Stadium': {'num_matches': 13,
  'total_runs': 4176,
  'total_wickets': 160,
  'avg_runs': 160.62,
  'prefered_toss_decision': 'field'},
 'Kingsmead': {'num_matches': 15,
  'total_runs': 4076,
  'total_wickets': 201,
  'avg_runs': 135.87,
  'prefered_toss_decision': 'bat'},
 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium': {'num_matches': 14,
  'total_runs': 4069,
  'total_wickets': 176,
  'avg_runs': 150.7,
  'prefered_toss_decision': 'field'},
 'Sardar Patel Stadium, Motera': {'num_matches': 12,
  'total_runs': 3589,
  'total_wickets': 145,
  'avg_runs': 138.04,
  'prefered_toss_decision': 'field'},
 'SuperSport Park': {'num_matches': 12,
  'total_runs': 3440,
  'total_wickets': 133,
  'avg_runs': 143.33,
  'prefered_toss_decision': 'bat'}}

In [72]:
ipl1

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN

In [73]:
ipl2.columns

Index(['match_id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2'],
      dtype='object')

## 3) season Summary

In [75]:
def season_winners():
    winning_team=(ipl2[ipl2['match_type']=='Final'][['season','winner']].to_dict(orient='records'))
    return winning_team

In [76]:
season_winners()

[{'season': 2008, 'winner': 'Rajasthan Royals'},
 {'season': 2009, 'winner': 'Sunrisers Hyderabad'},
 {'season': 2010, 'winner': 'Chennai Super Kings'},
 {'season': 2011, 'winner': 'Chennai Super Kings'},
 {'season': 2012, 'winner': 'Kolkata Knight Riders'},
 {'season': 2013, 'winner': 'Mumbai Indians'},
 {'season': 2014, 'winner': 'Kolkata Knight Riders'},
 {'season': 2015, 'winner': 'Mumbai Indians'},
 {'season': 2016, 'winner': 'Sunrisers Hyderabad'},
 {'season': 2017, 'winner': 'Mumbai Indians'},
 {'season': 2018, 'winner': 'Chennai Super Kings'},
 {'season': 2019, 'winner': 'Mumbai Indians'},
 {'season': 2020, 'winner': 'Mumbai Indians'},
 {'season': 2021, 'winner': 'Chennai Super Kings'},
 {'season': 2022, 'winner': 'Gujarat Titans'},
 {'season': 2023, 'winner': 'Chennai Super Kings'},
 {'season': 2024, 'winner': 'Kolkata Knight Riders'}]

In [77]:
ipl2

,match_id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2008,Bengaluru,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2008,Mohali,2008-04-19,League,MEK Hussey,Punjab Cricket Association IS Bindra Stadium,Punjab Kings,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2008,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Capitals,Rajasthan Royals,Rajasthan Royals,bat,Delhi Capitals,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2008,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2008,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Sunrisers Hyderabad,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,Rajiv Gandhi International Stadium,Punjab Kings,Sunrisers Hyderabad,Punjab Kings,bat,Sunrisers Hyderabad,wickets,4.0,215.0,20.0,N,NaN,Nitin Menon,VK Sharma
1091,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,Narendra Modi Stadium,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,160.0,20.0,N,NaN,AK Chaudhary,R Pandit
1092,1426310,2024,Ahmedabad,2024-05-22,Eliminator,R Ashwin,Narendra Modi Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,4.0,173.0,20.0,N,NaN,KN Ananthapadmanabhan,MV Saidharshan Kumar
1093,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,MA Chidambaram Stadium,Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,Sunrisers Hyderabad,runs,36.0,176.0,20.0,N,NaN,Nitin Menon,VK Sharma
1094,1426312,2024,Chennai,2024-05-26,Final,MA Starc,MA Chidambaram Stadium,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon